// bank2.js - Nivel 2: Intermedio (200 preguntas)
(function() {
var raw = [
// [pregunta, A, B, C, D, respuesta(0-3), fuente]
["¿Qué profeta del Antiguo Testamento predijo que el Mesías nacería en Belén?","Isaías","Jeremías","Miqueas","Amós",2,"Miqueas 5,1"],
["¿Cuántas parábolas contiene el capítulo 15 del Evangelio de Lucas?","1","2","3","4",2,"La oveja perdida, la moneda perdida y el hijo pródigo"],
["¿Qué libro bíblico narra el retorno del exilio a Jerusalén con Zorobabel?","Nehemías","Esdras","Crónicas","Macabeos",1,"Esdras 1-6"],
["¿Qué vio el siervo de Eliseo cuando el Señor le abrió los ojos en Dotán?","Dos ángeles guardando la entrada","Los montes llenos de caballos y carros de fuego","Un solo ángel con espada desenvainada","El ejército arameo huyendo",1,"2 Reyes 6,17 — Dios abrió los ojos del criado y vio la montaña llena de caballos y carros de fuego"],
["¿En qué parábola un padre divide su herencia antes de morir?","La del hijo pródigo","La de los talentos","La de los viñadores homicidas","La de los obreros de la viña",0,"Lucas 15,12"],
["¿Qué significa el nombre 'Israel' dado a Jacob?","El que lucha con Dios","El amado de Dios","El elegido de Dios","El siervo de Dios",0,"Génesis 32,29 — 'el que luchó con Dios'"],
["¿En qué río luchó Jacob con el ángel de Dios?","El Jordán","El Nilo","El Jaboc","El Éufrates",2,"Génesis 32,23"],
["¿Cuántos años vivió Matusalén, el hombre más anciano de la Biblia?","900","969","1000","800",1,"Génesis 5,27"],
["¿Qué mandó construir Moisés en el desierto como lugar de adoración?","El Templo","La Tienda del Encuentro (Tabernáculo)","Una ciudad santa","Un altar de piedra",1,"Éxodo 26"],
["¿Cuántos años estuvo Moisés en el desierto antes de volver a Egipto?","20","30","40","50",2,"Éxodo 7,7 — tenía 80 años cuando habló al faraón, había huido a los 40"],
["¿Qué propiedad especial tenía el agua que salió de la roca cuando Moisés la golpeó dos veces en Meribá?","Era agua santa","Era agua curativa","Era un milagro que Dios concedió a pesar de la desobediencia de Moisés","Era agua dulce en el desierto",2,"Números 20,8-12 — Moisés golpeó la roca dos veces en vez de hablarle"],
["¿Cuál fue la consecuencia para Moisés de golpear la roca en Meribá?","No murió","No entró a la Tierra Prometida","Perdió sus poderes","Fue exiliado",1,"Números 20,12"],
["¿Qué profetisa del Nuevo Testamento reconoció al niño Jesús en el Templo?","Débora","Isabel","Miriam","Ana",3,"Lucas 2,36-38"],
["¿Qué dijo Simeón cuando tuvo al niño Jesús en brazos?","'Este es el Hijo de Dios'","'Nunc dimittis' — 'Ahora puedes dejar ir a tu siervo en paz'","'Bendito sea Dios'","'Este es el Mesías'",1,"Lucas 2,29-32"],
["¿Cuántos años tenía Ana la profetisa cuando vio a Jesús en el Templo?","Más de 80 años","60 años","70 años","50 años",0,"Lucas 2,36-37"],
["¿En qué capítulo de Isaías se habla del Siervo Sufriente?","Isaías 7","Isaías 40","Isaías 52-53","Isaías 60",2,"Isaías 52,13-53,12"],
["¿Qué profecía de Isaías dice 'Una virgen concebirá y dará a luz un hijo'?","Isaías 9,5","Isaías 7,14","Isaías 40,3","Isaías 11,1",1,"Isaías 7,14"],
["¿Cuántas puertas tenía la Jerusalén celeste según el Apocalipsis?","7","10","12","15",2,"Apocalipsis 21,12"],
["¿Cuántos sellos tiene el libro que el Cordero abre en el Apocalipsis?","4","5","6","7",3,"Apocalipsis 5,1"],
["¿Cuántas trompetas suenan en el libro del Apocalipsis?","4","5","6","7",3,"Apocalipsis 8,2"],
["¿Qué número es llamado 'el número de la bestia' en el Apocalipsis?","616","666","777","888",1,"Apocalipsis 13,18"],
["¿Cuántas iglesias reciben cartas al inicio del Apocalipsis?","5","6","7","8",2,"Apocalipsis 1,4 — las 7 iglesias"],
["¿Cuál es el primer libro de la Biblia que menciona la circuncisión como señal de la alianza?","Éxodo","Números","Génesis","Deuteronomio",2,"Génesis 17,10"],
["¿En qué capítulo del Génesis Dios llama a Abrahán a salir de su tierra?","Génesis 3","Génesis 6","Génesis 12","Génesis 15",2,"Génesis 12,1-3"],
["¿Cómo se llama la promesa de Dios con Abrahán en Génesis 15?","El Decálogo","La Gran Comisión","La Alianza","La Ley",2,"Génesis 15 — la Alianza con Abrahán"],
["¿Cuántas veces aparece la frase 'Y vio Dios que era bueno' en el relato de la creación?","5","6","7","8",1,"Génesis 1 — 6 veces (más 'muy bueno' al final)"],
["¿En qué montaña recibió Moisés los diez mandamientos?","Monte Tabor","Monte Sinaí","Monte Carmelo","Monte Horeb",1,"Éxodo 19-20 (también llamado Horeb)"],
["¿Cómo se llama el libro de la ley que Josías encontró en el Templo?","Génesis","Levítico","Deuteronomio","Números",2,"2 Reyes 22,8 — se identifica con el Deuteronomio"],
["¿En qué momento del día apareció Dios a Moisés en el Sinaí?","Al amanecer","Al mediodía","Al atardecer","En medio de truenos y relámpagos",3,"Éxodo 19,16-18"],
["¿Quién fue el padre espiritual del profeta Eliseo?","Isaías","Samuel","Elías","Natán",2,"1 Reyes 19,19-21"],
["¿Qué profeta anunció que Dios escribiría la ley en los corazones (Nueva Alianza)?","Isaías","Ezequiel","Amós","Jeremías",3,"Jeremías 31,31-34"],
["¿En qué libro aparece la fórmula 'Yo soy el que soy' (YHWH)?","Números","Levítico","Éxodo","Deuteronomio",2,"Éxodo 3,14"],
["¿Cuántas letras tiene el alfabeto hebreo?","20","22","24","26",1,"22 letras"],
["¿Qué significa el tetragrámaton YHWH?","Señor de los ejércitos","El que es / el que existe","Dios altísimo","Mi pastor",1,"Del hebreo הוה-י — 'el que es/será'"],
["¿Cuál es el libro del AT que más cita el NT?","Génesis","Éxodo","Deuteronomio","Isaías y Salmos",3,"Salmos e Isaías son los más citados en el NT"],
["¿Cuántas veces se repite el salmo 118 (117 LXX)?","Es único","Aparece solo en el Salterio","Algunos versículos se repiten en el 136","Es idéntico al 119",2,"El Sal 136 repite '...porque es eterno su amor'"],
["¿Qué salmo es el más largo de la Biblia?","Salmo 119","Salmo 139","Salmo 51","Salmo 22",0,"Salmo 119 — 176 versículos"],
["¿Cuántas estrofas tiene el Salmo 119?","20","22","24","26",1,"22 estrofas, una por cada letra del alfabeto hebreo"],
["¿En qué evangelio aparece el Sermón del Monte?","Marcos","Lucas","Juan","Mateo",3,"Mateo 5-7"],
["¿Cómo se llama el discurso equivalente al Sermón del Monte en Lucas?","Discurso escatológico","Sermón de la Llanura","Discurso de envío","Discurso del pan de vida",1,"Lucas 6,17-49"],
["¿Cuántas parábolas contiene el capítulo 13 de Mateo?","5","7","8","10",1,"7 parábolas del Reino en Mt 13"],
["¿Cuál fue la primera parábola que Jesús explicó a sus discípulos?","La del hijo pródigo","La del trigo y la cizaña","La del grano de mostaza","La del sembrador",3,"Mateo 13,18-23"],
["¿Qué representa la semilla en la parábola del sembrador?","El creyente","El Espíritu Santo","La Palabra de Dios","La Iglesia",2,"Mateo 13,19"],
["¿Cuántos talentos recibió el siervo que enterró el dinero en la parábola?","5","3","2","1",3,"Mateo 25,15"],
["¿Cuántos talentos recibió el siervo más fiel en la parábola de los talentos?","1","2","3","5",3,"Mateo 25,15"],
["¿Cuántas vírgenes eran prudentes en la parábola de las diez vírgenes?","3","5","7","10",1,"Mateo 25,2"],
["¿Qué les faltó a las vírgenes necias?","Fe","Amor","Aceite para sus lámparas","Tiempo para orar",2,"Mateo 25,8"],
["¿Qué dice Jesús sobre orar en secreto?","Que no tiene mérito","Que Dios no puede escuchar","Que el Padre que ve en secreto recompensará abiertamente","Que es mejor en comunidad",2,"Mateo 6,6"],
["¿Cuántas peticiones tiene el Padrenuestro?","5","6","7","8",2,"7 peticiones en Mateo 6,9-13"],
["¿Qué significa 'Abba'?","Señor","Dios grande","Padre (con connotación filial íntima)","Santo",2,"Marcos 14,36; Romanos 8,15"],
["¿Cuál fue la primera 'tentación' que Satanás propuso a Jesús en el desierto?","Tirarse del Templo","Adorar a Satanás","Convertir piedras en pan","Apoderarse de todos los reinos",2,"Mateo 4,3"],
["¿Cómo respondió Jesús a la primera tentación?","Orando","'No solo de pan vive el hombre'","'Adorarás al Señor tu Dios'","Huyendo",1,"Mateo 4,4; Deuteronomio 8,3"],
["¿Qué cita Jesús como respuesta a las tres tentaciones en el desierto?","Los Salmos","Isaías","Deuteronomio","Génesis",2,"Mateo 4,4.7.10 — los tres del Deuteronomio"],
["¿En qué evangelio Jesús dice 'Yo soy la resurrección y la vida'?","Mateo","Marcos","Lucas","Juan",3,"Juan 11,25"],
["¿Cuántos 'Yo soy' pronuncia Jesús en el Evangelio de Juan?","4","5","6","7",3,"7 'Yo soy' con predicado en Juan"],
["¿Cuál es el primer 'Yo soy' en Juan?","'Yo soy la vid'","'Yo soy el pan de vida'","'Yo soy la luz del mundo'","'Yo soy el camino'",1,"Juan 6,35"],
["¿Qué milagro hizo Jesús en el estanque de Betesda?","Curó a un leproso","Multiplicó panes","Curó a un ciego de nacimiento","Curó a un paralítico que llevaba 38 años enfermo",3,"Juan 5,5"],
["¿Qué les dijo Jesús a los fariseos sobre el pan de vida?","'El que coma este pan vivirá para siempre'","'Este pan es mi cuerpo'","'Yo soy el pan que bajó del cielo'","Las tres son frases de Juan 6",3,"Juan 6,35-58"],
["¿Qué hizo Jesús cuando la mujer adúltera fue llevada ante él?","La juzgó","La perdonó directamente sin más","Escribió en el suelo y dijo 'quien esté sin pecado tire la primera piedra'","Enseñó sobre el matrimonio",2,"Juan 8,6-11"],
["¿Qué afirmó Jesús antes de resucitar a Lázaro?","'Todo poder me ha sido dado'","'Soy el buen pastor'","'Yo soy la resurrección y la vida'","'Soy el Hijo de Dios'",2,"Juan 11,25"],
["¿Cuál fue la señal que Jesús dio a los fariseos cuando pidieron una señal?","El milagro de la multiplicación","La curación del paralítico","La señal de Jonás","La transfiguración",2,"Mateo 12,39-40"],
["¿Qué significa la 'señal de Jonás' que Jesús dio?","40 días de predicación","3 días en el seno de la tierra como Jonás en el pez","Un signo en el cielo","Un terremoto",1,"Mateo 12,40"],
["¿Dónde fue transfigurado Jesús?","Monte Carmelo","Monte Sinaí","Monte de los Olivos","Monte Tabor (según la tradición)",3,"Mateo 17,1-2 — 'un monte alto'"],
["¿Quiénes aparecieron junto a Jesús en la Transfiguración?","Elías y Samuel","Moisés y Elías","Abraham y Moisés","David y Elías",1,"Mateo 17,3"],
["¿Qué dijo la voz del cielo en la Transfiguración?","'Este es mi siervo'","'Este es el Mesías'","'Este es mi Hijo amado, escuchadle'","'Aleluya'",2,"Mateo 17,5"],
["¿Qué mandamiento nuevo dio Jesús en la Última Cena?","'Amad a Dios sobre todas las cosas'","'Que os améis los unos a los otros como yo os he amado'","'Predicad el Evangelio'","'Guardad mis mandamientos'",1,"Juan 13,34"],
["¿Cuándo instituyó Jesús la Eucaristía?","En la multiplicación de los panes","En la Última Cena","En las Bodas de Caná","En la oración del huerto",1,"Mateo 26,26-28"],
["¿Qué hizo Jesús antes de la Última Cena que sorprendió a los discípulos?","Oró en voz alta","Lavó los pies de los discípulos","Multiplicó el vino","Resucitó a un muerto",1,"Juan 13,5"],
["¿En qué noche se celebró la Última Cena?","Noche del sábado","Primera noche de la Pascua judía","Noche del Pentecostés","Noche de luna nueva",1,"Mateo 26,17-19"],
["¿Cuántos capítulos tiene el Evangelio de Marcos?","14","15","16","17",2,"16 capítulos"],
["¿En qué evangelio se menciona más veces la palabra 'inmediatamente'?","Mateo","Marcos","Lucas","Juan",1,"Marcos usa εὐθύς (inmediatamente) unas 40 veces"],
["¿Para qué comunidad se cree que escribió Marcos su evangelio?","Para judíos de Palestina","Para gentiles de Roma","Para griegos de Éfeso","Para la comunidad de Antioquía",1,"Marcos escribió para gentiles, probablemente en Roma"],
["¿Cuántos capítulos tiene el Evangelio de Lucas?","22","23","24","25",2,"24 capítulos"],
["¿Cómo comienza el Evangelio de Lucas?","'En el principio era el Verbo'","'El libro de la genealogía de Jesucristo'","'Inicio del Evangelio de Jesucristo'","Un prólogo dedicado a Teófilo",3,"Lucas 1,1-4 — dedicado a Teófilo"],
["¿A quién dedicó Lucas su evangelio y el libro de Hechos?","A Plinio","A Teófilo","A Cornelio","A Priscila",1,"Lucas 1,3; Hechos 1,1"],
["¿Qué texto del AT usa Jesús en la sinagoga de Nazaret para presentar su misión?","Isaías 40,3","Isaías 53","Isaías 61,1-2","Miqueas 5,1",2,"Lucas 4,18 — Is 61,1-2"],
["¿Qué dijo la gente de Nazaret cuando Jesús predicó en la sinagoga?","'Grande es su sabiduría'","'Bendito sea Dios'","'¿No es este el hijo de José?'","'Nunca nadie habló así'",2,"Lucas 4,22"],
["¿Qué le dijo Jesús a la gente de Nazaret sobre los profetas?","'Vosotros sois hijos de los profetas'","'El profeta no es bien recibido en su propia tierra'","'Los profetas predicaron aquí'","'Cumplid la ley'",1,"Lucas 4,24"],
["¿Cuántos días ayunó Moisés en el Sinaí?","20","30","40","50",2,"Éxodo 34,28"],
["¿Cuántos ancianos eligió Moisés para gobernar al pueblo?","12","24","70","72",2,"Números 11,16 — 70 ancianos"],
["¿A cuántos discípulos envió Jesús de dos en dos según Lucas 10?","12","24","70","72",3,"Lucas 10,1 — 72 según la mayoría de manuscritos"],
["¿Cuál es la primera bienaventuranza del Sermón del Monte?","'Bienaventurados los puros de corazón'","'Bienaventurados los misericordiosos'","'Bienaventurados los pobres de espíritu'","'Bienaventurados los que lloran'",2,"Mateo 5,3"],
["¿Cuántos capítulos tiene el libro de Génesis?","40","45","50","55",2,"50 capítulos"],
["¿Cuántos capítulos tiene el libro del Éxodo?","30","35","40","45",2,"40 capítulos"],
["¿Cuántos capítulos tiene el libro de los Salmos?","120","130","140","150",3,"150 Salmos = 150 capítulos"],
["¿Qué título tiene el salmo que comienza 'El Señor es mi luz y mi salvación'?","Salmo 22","Salmo 27","Salmo 46","Salmo 121",1,"Salmo 27,1"],
["¿En qué salmo aparece la frase 'Dios mío, Dios mío, ¿por qué me has abandonado'?","Salmo 22","Salmo 23","Salmo 51","Salmo 118",0,"Salmo 22,2 — citado por Jesús en la cruz"],
["¿Qué dijo Jesús en la cruz citando el Salmo 22?","'Padre, perdónalos'","'Todo está cumplido'","'Dios mío, Dios mío, ¿por qué me has abandonado?'","'En tus manos encomiendo mi espíritu'",2,"Marcos 15,34; Mateo 27,46"],
["¿Cuántas 'palabras' pronunció Jesús desde la cruz?","5","6","7","8",2,"Las 7 palabras de Cristo en la cruz"],
["¿Qué dijo Jesús primero desde la cruz?","'Tengo sed'","'Padre, en tus manos encomiendo mi espíritu'","'Padre, perdónalos porque no saben lo que hacen'","'Todo está cumplido'",2,"Lucas 23,34"],
["¿A quién encomendó Jesús su madre desde la cruz?","A Pedro","A Santiago","A María Magdalena","Al discípulo amado (Juan)",3,"Juan 19,26-27"],
["¿Qué dijo Jesús como última palabra en el Evangelio de Juan?","'Consumatum est' — Todo está cumplido","'Padre, perdónalos'","'¿Por qué me has abandonado?'","'En tus manos'",0,"Juan 19,30"],
["¿Cuántos capítulos tiene el libro de los Hechos de los Apóstoles?","24","26","28","30",2,"28 capítulos"],
["¿En qué ciudad comenzó la primera persecución contra los cristianos?","Roma","Éfeso","Antioquía","Jerusalén",3,"Hechos 8,1"],
["¿Quién dispersó a los primeros cristianos fuera de Jerusalén?","Los romanos","Los griegos","La persecución que siguió al martirio de Esteban","Los zelotes",2,"Hechos 8,1"],
["¿En qué ciudad predicó Pablo junto con Bernabé por primera vez de modo amplio?","Roma","Éfeso","Corinto","Antioquía de Pisidia",3,"Hechos 13,14"],
["¿Cuántos viajes misioneros hizo Pablo según el libro de los Hechos?","2","3","4","5",1,"3 viajes misioneros principales en Hechos"],
["¿En qué ciudad Pablo predicó en el Areópago (Colina de Marte)?","Corinto","Éfeso","Atenas","Tesalónica",2,"Hechos 17,19-22"],
["¿Qué dijo Pablo sobre el altar 'Al dios desconocido' en Atenas?","Que era superstición","'Lo que adoráis sin conocer, eso os anuncio yo'","Que había que destruirlo","Que los griegos estaban perdidos",1,"Hechos 17,23"],
["¿Cuántos capítulos tiene la carta a los Romanos?","14","15","16","17",2,"16 capítulos"],
["¿Cuál es la carta más larga de Pablo?","Gálatas","1 Corintios","Romanos","Hebreos",2,"Romanos — 16 capítulos"],
["¿En qué carta Pablo describe el himno a la caridad (amor)?","Romanos","Efesios","Colosenses","1 Corintios",3,"1 Corintios 13"],
["¿Cuántas cualidades del amor enumera Pablo en 1 Corintios 13?","8","12","15","7",1,"1 Corintios 13,4-7 — 15 características"],
["¿Qué imagen usa Pablo para la Iglesia en 1 Corintios 12?","Un templo","Un cuerpo con muchos miembros","Una familia","Un ejército",1,"1 Corintios 12,12-27"],
["¿En qué carta Pablo escribe el himno cristológico 'el que siendo de condición divina...'?","Romanos","Efesios","Colosenses","Filipenses",3,"Filipenses 2,6-11"],
["¿En qué carta aparece el himno al Cristo primogénito 'Él es imagen del Dios invisible'?","Efesios","Filipenses","Colosenses","Hebreos",2,"Colosenses 1,15-20"],
["¿Cuántas cartas pastorales escribió Pablo?","2","3","4","5",1,"3 cartas pastorales: 1 y 2 Timoteo, Tito"],
["¿Qué carta de Pablo está dirigida a una comunidad en la actual Turquía?","Romanos","Corintios","Gálatas","Filipenses",2,"Gálatas — Galacia está en la actual Turquía"],
["¿Cuántas cartas 'de la cautividad' tiene Pablo?","2","3","4","5",2,"4 cartas: Efesios, Filipenses, Colosenses, Filemón"],
["¿A qué personaje está dirigida la carta más corta de Pablo?","Timoteo","Tito","Filemón","Apolo",2,"Filemón — 1 capítulo"],
["¿Cuántos capítulos tiene la carta a los Gálatas?","4","5","6","7",2,"6 capítulos"],
["¿Qué dice Pablo sobre la ley y la fe en Gálatas?","La ley salva","Somos justificados por la fe, no por las obras de la ley","La ley y la fe son iguales","La ley fue dada por ángeles malos",1,"Gálatas 2,16"],
["¿En qué carta Pablo dice 'Todo lo puedo en aquel que me da fuerzas'?","Romanos","Efesios","Colosenses","Filipenses",3,"Filipenses 4,13"],
["¿En qué carta Pablo pide que se ayude a una mujer llamada Febe?","Gálatas","Efesios","Romanos","Filipenses",2,"Romanos 16,1-2"],
["¿Cuántos capítulos tiene el libro de Isaías?","54","60","66","72",2,"66 capítulos"],
["¿En qué capítulo de Isaías aparece el 'Cántico del Siervo Sufriente'?","Isaías 7","Isaías 40","Isaías 53","Isaías 60",2,"Isaías 52,13-53,12"],
["¿Cuántas partes tiene el libro de Isaías según los críticos?","2","3","4","5",1,"3 partes: Proto (1-39), Déutero (40-55), Trito (56-66)"],
["¿Qué visión tuvo Isaías en el año que murió el rey Ozías?","La rueda de fuego","El Siervo de Yahvé","Los cuatro seres vivientes","Los serafines y el trono de Dios",3,"Isaías 6,1-8"],
["¿Qué dijo Isaías cuando vio la gloria de Dios?","'Aleluya'","'¡Ay de mí, que estoy perdido!'","'Santo, Santo, Santo'","'Glorificad al Señor'",1,"Isaías 6,5"],
["¿Con qué purificó el serafín los labios de Isaías?","Con agua del Templo","Con un carbón encendido del altar","Con aceite sagrado","Con su soplo",1,"Isaías 6,6-7"],
["¿Qué respondió Isaías cuando Dios preguntó '¿A quién enviaré?'?","'Envía a otro'","'No soy digno'","'Heme aquí, envíame a mí'","'Tu siervo está listo'",2,"Isaías 6,8"],
["¿Cuántos capítulos tiene el libro de Jeremías?","46","48","52","54",2,"52 capítulos"],
["¿Cómo se llama el libro de los lamentos de Jeremías?","Lamentaciones","Trenos","Lamentaciones o Trenos (ambas son correctas)","Trenos o Lamentaciones según la tradición",2,"Lamentaciones / Trenos de Jeremías"],
["¿Cuántos capítulos tiene el libro de Ezequiel?","40","44","48","52",2,"48 capítulos"],
["¿Qué visión inaugura el libro de Ezequiel?","La del Templo nuevo","La del Valle de huesos secos","Los querubines y el trono de Yahvé (la merkabá)","El Río del Templo",2,"Ezequiel 1 — la visión de la merkabá"],
["¿Cuántos capítulos tienen los libros de los Doce Profetas Menores en total?","67","68","69","70",0,"67 capítulos en los 12 profetas menores"],
["¿Cuál es el profeta menor más corto?","Abdías","Nahúm","Hageo","Sofonías",0,"Abdías — 1 capítulo, 21 versículos"],
["¿Cuál es el profeta menor más largo?","Oseas","Amós","Zacarías","Miqueas",2,"Zacarías — 14 capítulos"],
["¿Qué profeta anunció 'Y sucederá después que derramaré mi Espíritu sobre toda carne'?","Isaías","Jeremías","Amós","Joel",3,"Joel 3,1 — citado en Hechos 2,17"],
["¿Cuál es el profeta que más se parece en su mensaje al de Juan el Bautista?","Oseas","Amós","Abdías","Malaquías",3,"Malaquías 3,1 — 'enviará a mi mensajero'"],
["¿Cuál es el último libro del Antiguo Testamento?","Zacarías","Malaquías","Abdías","Daniel",1,"Malaquías"],
["¿Qué evento describe el final del libro de Malaquías?","La llegada del Mesías","La vuelta del exilio","La venida del día del Señor y de Elías","La reconstrucción del Templo",2,"Malaquías 3,23-24"],
["¿Cuántos capítulos tiene el Deuteronomio?","30","32","34","36",2,"34 capítulos"],
["¿Cuáles son los dos textos que Jesús cita como resumen de toda la ley?","Ex 20 y Lv 19","Dt 6,4-5 y Lv 19,18","Gn 1 y Ex 20","Is 61 y Jr 31",1,"Marcos 12,29-31 — el Shemá y Lv 19,18"],
["¿Cómo se llama el credo del pueblo judío que comienza 'Escucha, Israel'?","La Torá","El Shemá","El Talmud","La Mishná",1,"Deuteronomio 6,4 — שְׁמַע יִשְׂרָאֵל"],
["¿Cuántos capítulos tiene el libro del Levítico?","24","25","27","30",2,"27 capítulos"],
["¿Qué libro bíblico contiene las leyes de pureza y los sacrificios?","Éxodo","Números","Deuteronomio","Levítico",3,"Levítico"],
["¿Cuántos capítulos tiene el libro de los Números?","32","34","36","38",2,"36 capítulos"],
["¿Qué libro narra el censo del pueblo de Israel en el desierto?","Levítico","Éxodo","Números","Deuteronomio",2,"Números — de ahí el nombre"],
["¿Cuántos capítulos tiene el libro de Josué?","22","24","26","28",1,"24 capítulos"],
["¿Cuántos capítulos tiene el libro de los Jueces?","19","21","23","25",1,"21 capítulos"],
["¿Cuántos capítulos tienen los dos libros de Samuel juntos?","44","52","55","60",1,"1Sam (31) + 2Sam (24) = 55"],
["¿Cuántos capítulos tienen los dos libros de los Reyes juntos?","42","44","46","48",2,"1Re (22) + 2Re (25) = 47"],
["¿En qué libro del AT aparece la frase 'Amarás a tu prójimo como a ti mismo'?","Números","Deuteronomio","Levítico","Génesis",2,"Levítico 19,18"],
["¿Cómo se llama el libro del AT que narra la reconstrucción del Templo tras el exilio?","Esdras","Nehemías","Ageo","Esdras y Nehemías junto con Ageo y Zacarías",0,"Esdras y Nehemías narran la restauración"],
["¿En qué libro del AT aparece la escena del Valle de los huesos secos?","Isaías","Jeremías","Daniel","Ezequiel",3,"Ezequiel 37,1-14"],
["¿Qué simbolizan los huesos secos en Ezequiel 37?","La muerte física","El pecado del pueblo","La resurrección al final de los tiempos","El exilio y la futura restauración de Israel",3,"Ezequiel 37,11-14"],
["¿Cuál fue la señal que Dios pidió a Gedeón?","El toque de la trompeta","El vellón de lana mojado/seco (milagro del rocío)","Una estrella en el cielo","El sonido del viento",1,"Jueces 6,36-40"],
["¿Con cuántos hombres venció Gedeón al ejército madianita?","300","3000","10000","30000",0,"Jueces 7,7"],
["¿Con qué armas sorprendió Gedeón a los madianitas?","Espadas y lanzas","Cántaros y antorchas con trompetas","Arcos y flechas","Solo con gritos",1,"Jueces 7,16-22"],
["¿Quién fue el juez que se suicidó aplastando el templo de los filisteos?","Gedeón","Jefté","Débora","Sansón",3,"Jueces 16,30"],
["¿En qué profeta del AT aparece la imagen de Dios como esposo e Israel como esposa infiel?","Amós","Jeremías","Miqueas","Oseas",3,"Oseas 1-3"],
["¿Qué profeta del AT proclamó 'Solo corre el derecho como el agua'?","Miqueas","Oseas","Abdías","Amós",3,"Amós 5,24"],
["¿Qué profeta del AT es llamado 'el profeta de los pobres'?","Zacarías","Hageo","Sofonías","Amós",3,"Amós — defensor de los pobres"],
["¿En qué libro se encuentra el Magnificat de María?","Mateo","Marcos","Juan","Lucas",3,"Lucas 1,46-55"],
["¿En qué libro se encuentra el Benedictus de Zacarías?","Mateo","Marcos","Juan","Lucas",3,"Lucas 1,68-79"],
["¿En qué libro se encuentra el Nunc Dimittis de Simeón?","Mateo","Marcos","Juan","Lucas",3,"Lucas 2,29-32"],
["¿Cuántos himnos hay en el prólogo de Lucas (capítulos 1-2)?","2","3","4","5",1,"Magnificat, Benedictus, Gloria in excelsis, Nunc Dimittis"],
["¿Cuántos capítulos tiene el libro de los Hechos de los Apóstoles?","24","26","28","30",2,"28 capítulos"],
["¿Cuántas cartas de Juan hay en el Nuevo Testamento?","2","3","4","5",1,"3 cartas de Juan"],
["¿Cuántas cartas de Pedro hay en el Nuevo Testamento?","1","2","3","4",1,"2 cartas de Pedro"],
["¿Quién escribió la carta a los Hebreos?","Pablo","Apolo","Pedro","Autor desconocido",3,"Hebreos — autor incierto en la Biblia"],
["¿Cuántos capítulos tiene la carta a los Hebreos?","11","12","13","14",2,"13 capítulos"],
["¿Quién es presentado en la carta a los Hebreos como 'sumo sacerdote eterno según el orden de Melquisedec'?","David","Moisés","Elías","Jesús",3,"Hebreos 5,10; 7,17"],
["¿Quién fue Melquisedec?","Un profeta de Israel","Rey de Salem y sacerdote del Dios Altísimo","Un juez de Israel","Un sacerdote levita",1,"Génesis 14,18; Hebreos 7"],
["¿Cuántos capítulos tiene la carta de Santiago?","3","4","5","6",2,"5 capítulos"],
["¿Qué dice Santiago sobre la fe sin obras?","Que es suficiente","Que es un don de Dios","Que está muerta","Que es lo más importante",2,"Santiago 2,26"],
["¿Cuántos capítulos tiene el Apocalipsis?","20","21","22","23",2,"22 capítulos"],
["¿Quién es el Cordero en el Apocalipsis?","Un ángel","La Iglesia","El Espíritu Santo","Jesucristo",3,"Apocalipsis 5,6-7"],
["¿Cuántas copas de ira hay en el Apocalipsis?","5","6","7","8",2,"Apocalipsis 15-16 — 7 copas"],
["¿Qué ciudad es llamada 'Babilonia' en el Apocalipsis?","Jerusalén","Antioquía","Alejandría","Roma",3,"Apocalipsis 17-18 — Roma"],
["¿En qué libro se describe la 'Nueva Jerusalén'?","Daniel","Ezequiel","Zacarías","Apocalipsis",3,"Apocalipsis 21"],
["¿Cuántos capítulos tienen los dos libros de los Macabeos juntos?","26","28","30","32",1,"1Mac (16) + 2Mac (15) = 31"],
["¿Cuál es el único libro del AT escrito originalmente en griego?","Eclesiastés","Sabiduría","Sirácida","Ester",1,"2 Macabeos es griego; Sabiduría también — ambas son posibles respuestas, pero Sabiduría es la más citada"],
["¿En qué libro del AT se encuentra la historia del joven Tobías y el ángel Rafael?","Ester","Judit","Tobías","Baruc",2,"Libro de Tobías"],
["¿Qué ángel guió a Tobías en su viaje?","Gabriel","Miguel","Rafael","Uriel",2,"Tobías 5,4"],
["¿Cuál es el único libro del AT donde aparece el nombre del arcángel Rafael?","Daniel","Tobías","Baruc","Judith",1,"Tobías 12,15"],
["¿Cuántos libros deuterocanónicos tienen el Antiguo Testamento católico?","5","6","7","8",2,"7 libros: Tobías, Judit, 1Mac, 2Mac, Sabiduría, Sirácida, Baruc (y partes de Ester y Daniel)"],
["¿Por qué los libros deuterocanónicos no están en la Biblia protestante?","Porque son apócrifos","Porque no estaban en el canon hebreo de Jamnia","Porque los escribieron griegos","Porque son más recientes que el NT",1,"El canon hebreo de Jamnia (90 d.C.) no los incluyó; el NT los cita"],
["¿En qué concilio definió la Iglesia Católica el canon de los 73 libros?","Nicea","Éfeso","Trento","Vaticano I",2,"Concilio de Trento, 1546"],
["¿Qué es el 'Canon de Alejandría'?","El canon hebreo","El canon protestante","El NT griego","La Septuaginta con los libros deuterocanónicos",3,"La LXX incluía los deuterocanónicos usados por los LXX de Alejandría"],
["¿Cuántos capítulos tiene el libro de Job?","38","40","42","44",2,"42 capítulos"],
["¿Cuántos amigos visitaron a Job en su sufrimiento?","2","3","4","5",1,"Job 2,11 — Elifaz, Bildad, Sofar; después Elihú"],
["¿Cómo se llama el adversario celestial en el libro de Job?","Leviatán","Behemot","Asmodeo","El Adversario (HaSatán)",3,"Job 1,6-12 — השָׂטָן, el Adversario"],
["¿Cómo respondió Job a la voz de Dios desde el torbellino?","Con ira","Con más preguntas","Con confesión y adoración","Con silencio total",2,"Job 40,3-5; 42,1-6"]
];
raw.forEach(function(r){
    allQuestions.push({question:r[0],options:[r[1],r[2],r[3],r[4]],answer:r[5],difficulty:2,money:500,isSafeHaven:false,source:r[6]});
});
})();
