// bank4.js - Nivel 4: Superior (200 preguntas)
(function() {
var raw = [
// [pregunta, A, B, C, D, respuesta(0-3), fuente]
["¿Cuál es el único evangelio que menciona la resurrección de los santos en el momento de la muerte de Jesús?","Marcos","Lucas","Juan","Mateo",3,"Mateo 27,52-53 — los santos resucitan y aparecen en Jerusalén"],
["¿En qué versículo de Mateo Jesús llora?","Mateo 26,75","Mateo 27,46","No figura en Mateo; está en Juan 11,35","Mateo 19,14",2,"Jesús llora en Juan 11,35 — en Mateo no se menciona explícitamente"],
["¿Qué versículo de la Biblia es considerado el más corto?","Juan 11,35","Juan 3,16","Lucas 20,30","Génesis 1,1",0,"Juan 11,35 — 'Jesús lloró' (ἐδάκρυσεν ὁ Ἰησοῦς)"],
["¿Qué versículo es llamado 'el Evangelio en miniatura'?","Marcos 1,1","Juan 1,14","Juan 3,16","Romanos 1,16",2,"Juan 3,16 — 'tanto amó Dios al mundo...'"],
["¿Qué ciudad corresponde a la antigua 'Ur de los caldeos' de donde salió Abrahán?","La actual Mosul (Iraq)","La actual Tel el-Mukayyar (Iraq)","La actual Bagdad","La actual Damasco",1,"Ur se identifica con Tell el-Mukayyar en el sur de Iraq"],
["¿Qué significa el hebreo 'Canaan' (כְּנַעַן)?","La tierra prometida","El país de la púrpura / de los comerciantes","La tierra de Dios","El país de los cedros",1,"כְּנַעַן — relacionado con el comercio o la púrpura"],
["¿Cuántos reyes derrotó Josué en la conquista de Canaán según Josué 12?","20","28","31","36",2,"Josué 12,24 — 31 reyes derrotados"],
["¿Qué río marcó el límite norte de la tierra prometida?","El Éufrates","El Orontes","El Eleutero","El Jordán",0,"El Éufrates era el límite norte ideal (Dt 1,7; 11,24)"],
["¿Cuántos metros bajo el nivel del mar se encuentra el Mar Muerto?","200 m","350 m","430 m","500 m",2,"El Mar Muerto está a unos 430 m bajo el nivel del mar"],
["¿Cómo se llamaba Hebrón en tiempos de los patriarcas?","Mamré / Quiryat-Arbá","Jaboc","Siquén","Betel",0,"Génesis 23,2 — Hebrón = Quiryat-Arbá / Mamré"],
["¿Dónde compró Abrahán una sepultura para Sara?","En Mamré","En Beersheba","En la cueva de Macpelá (Hebrón)","En Siquén",2,"Génesis 23,17-20 — la cueva de Macpelá"],
["¿Quién fue el primer rey no israelita que se convierte en el AT?","Nabucodonosor","Ciro el Grande","El faraón de José","Darío el medo",0,"Daniel 4 — Nabucodonosor reconoce al Dios de Israel"],
["¿En qué texto del AT aparece la fórmula de la alianza 'vosotros seréis mi pueblo y yo seré vuestro Dios'?","Gn 17","Ex 6,7","Lv 26,12","Todas las anteriores y más",3,"Ez 36,28; Jr 7,23; Lv 26,12 — fórmula de la alianza"],
["¿Cuántos animales impuros se mencionan en Levítico 11?","10","15","20","Más de 20",3,"Lv 11 lista numerosos animales impuros — cerdos, liebres, camarones, etc."],
["¿Qué día del año podía entrar el sumo sacerdote al Santo de los Santos?","El sábado","El día de la Pascua","El Yom Kipur (Día del Gran Perdón)","El primer día del mes",2,"Levítico 16 — el Gran Día del Perdón"],
["¿Qué se realizaba el Día del Perdón (Yom Kipur) con el macho cabrío?","Se sacrificaba en el altar","Se enviaba al desierto cargando los pecados del pueblo (chivo expiatorio)","Se daba al pueblo para comer","Se quemaba fuera del campamento",1,"Levítico 16,21-22 — el macho cabrío para Azazel"],
["¿Qué es el 'Urim y Tumim' que llevaba el sumo sacerdote?","Dos velas sagradas","Las tablas de la ley en miniatura","Objetos para consultar la voluntad de Dios (suerte sagrada)","El incensario especial",2,"Éxodo 28,30 — Urim y Tumim para la consulta divina"],
["¿Cuántas piedras preciosas tenía el pectoral del sumo sacerdote?","10","12","14","16",1,"Éxodo 28,17-20 — 12 piedras, una por cada tribu"],
["¿Qué tribu no recibió herencia territorial en la tierra prometida?","Dan","Neftalí","Leví","Zabulón",2,"Números 18,20 — los levitas no tienen herencia territorial"],
["¿Cuántas ciudades de refugio estableció Moisés a este del Jordán?","1","2","3","4",2,"Números 35,11; Deuteronomio 4,41-43 — 3 ciudades al este"],
["¿Cuántas ciudades de refugio había en total?","3","6","9","12",1,"6 ciudades de refugio (3 al este y 3 al oeste del Jordán)"],
["¿Qué rey de Israel dividió el reino construyendo dos becerros de oro?","Salomón","Roboam","Jeroboam I","Ajab",2,"1 Reyes 12,28-29 — Jeroboam I en Betel y Dan"],
["¿En qué año cayó el Reino del Norte (Israel/Samaria) ante los asirios?","722 a.C.","586 a.C.","612 a.C.","538 a.C.",0,"2 Reyes 17 — 722 a.C., bajo Sargón II de Asiria"],
["¿En qué año cayó Jerusalén (Reino del Sur/Judá) ante los babilonios?","722 a.C.","597 a.C.","586 a.C.","539 a.C.",2,"2 Reyes 25 — 586 a.C., bajo Nabucodonosor II"],
["¿Quién fue el rey asirio que deportó las 10 tribus del Norte?","Tiglat-Pileser III","Salmanasar V","Sargón II","Senaquerib",2,"2 Reyes 17,6 — Sargón II deportó a Samaria"],
["¿Quién fue el rey babilónico que destruyó Jerusalén y el Templo?","Nabopolasar","Nabucodonosor II","Belsasar","Evil-Merodac",1,"2 Reyes 25 — Nabucodonosor II"],
["¿En qué año el edicto de Ciro permitió a los judíos regresar del exilio?","587 a.C.","539 a.C.","538 a.C.","515 a.C.",2,"Esdras 1,1-4 — 538 a.C."],
["¿En qué año fue reconstruido el Segundo Templo?","538 a.C.","520 a.C.","515 a.C.","444 a.C.",2,"Esdras 6,15 — 515 a.C., bajo Darío I"],
["¿Quién fue el profeta que animó a reconstruir el Templo junto con Zacarías?","Amós","Malaquías","Hageo","Abdías",2,"Hageo 1,1 — ca. 520 a.C."],
["¿En qué año reconstruyó Nehemías los muros de Jerusalén?","538 a.C.","515 a.C.","445 a.C.","333 a.C.",2,"Nehemías 6,15 — 445 a.C., en 52 días"],
["¿Cuántos días tardó Nehemías en reconstruir los muros de Jerusalén?","40","52","70","90",1,"Nehemías 6,15 — 52 días"],
["¿Qué rey persa fue el patrono del retorno de Esdras?","Ciro","Darío I","Jerjes","Artajerjes I",3,"Esdras 7,1-10 — Artajerjes I, ca. 458 a.C."],
["¿Cuántas millas de largo tenía el Templo de Herodes en su plataforma?","400 m×200 m","480 m×300 m","500 m×400 m","600 m×200 m",1,"Aprox. 480 m de N-S y 300 m de E-O en la plataforma"],
["¿En qué año comenzó Herodes el Grande la remodelación del Templo de Jerusalén?","37 a.C.","20 a.C.","10 a.C.","6 a.C.",1,"20/19 a.C. — Josefo, Antigüedades XV,380"],
["¿En qué año fue destruido el Templo por los romanos?","63 d.C.","66 d.C.","70 d.C.","73 d.C.",2,"70 d.C. — bajo el general Tito"],
["¿En qué año cayó la fortaleza de Masada?","70 d.C.","73 d.C.","74 d.C.","75 d.C.",1,"73-74 d.C. — Masada, último reducto zelote"],
["¿Qué procurador romano presidió la guerra contra los judíos en 66-70 d.C.?","Poncio Pilato","Félix","Festo","Floro (inicio) — Vespasiano y luego Tito (campaña)",3,"Gesio Floro provocó la revuelta; Vespasiano y Tito la aplastaron"],
["¿Quién escribió 'La guerra judía' y 'Antigüedades judías', fuentes externas del NT?","Filón de Alejandría","Josefo Flavio","Tácito","Plinio el Joven",1,"Josefo Flavio (37 - ca. 100 d.C.)"],
["¿Qué dice Josefo sobre Jesús en sus Antigüedades judías?","Nada en absoluto","El llamado 'Testimonium Flavianum' (con interpolaciones)","Lo llama un falso profeta","Lo menciona solo como hermano de Santiago",1,"Antigüedades 18,63-64 — el controvertido Testimonium Flavianum"],
["¿Cuántas 'semanas de años' aparecen en la profecía de las 70 semanas de Daniel?","60","70","77","490",1,"Daniel 9,24 — 70 semanas (שָׁבוּעִים = semanas de años = 490 años)"],
["¿Qué número de capítulo y versículo en el Apocalipsis contiene '666'?","Ap 13,8","Ap 13,18","Ap 17,5","Ap 6,6",1,"Apocalipsis 13,18"],
["¿Cuál es la variante textual antigua del número de la bestia en el Apocalipsis?","616","660","676","636",0,"Algunos manuscritos dan '616' en lugar de '666'"],
["¿Qué método exegético judío permite leer el '666' como una persona concreta?","Gematría","Midrash","Pesher","Targum",0,"Gematría — suma del valor numérico de las letras"],
["¿A qué persona histórica apunta el '666' en la gematría hebrea?","Domiciano","Nerón César (nrwn qsr en hebreo)","Vespasiano","Antíoco IV",1,"Nerón César en hebreo: נ(50)+ר(200)+ו(6)+ן(50)+ק(100)+ס(60)+ר(200) = 666"],
["¿Qué es el método 'pesher' de interpretación bíblica?","Un comentario alegórico","Una interpretación actualizada de textos proféticos para la comunidad del intérprete","Una traducción literal","Una paráfrasis para el pueblo",1,"Pesher — Qumrán, interpretación actualizada de los profetas"],
["¿Cuántos rollos del Mar Muerto se encontraron en Qumrán?","80","350","800 aprox.","2000",2,"Unos 900-1000 rollos en total (fragmentos y completos)"],
["¿En qué año se descubrieron los primeros rollos del Mar Muerto?","1945","1947","1950","1952",1,"1947 — en la cueva 1 de Qumrán"],
["¿Quiénes son los autores más probables de los rollos del Mar Muerto?","Los fariseos","Los zelotes","Los esenios","Los samaritanos",2,"Los esenios — comunidad de Qumrán"],
["¿Qué es el 'Documento de Damasco' de Qumrán?","Un texto legal de la comunidad esenia","El Templo de Qumrán","Una carta de guerra","Una liturgia de la comunidad",0,"El CD — regla comunitaria de los esenios"],
["¿Cuántos fragmentos del libro de Isaías se encontraron en Qumrán?","1","2 rollos completos y fragmentos","5","21",1,"El Gran Rollo de Isaías (1QIsa^a) y fragmentos de 1QIsa^b"],
["¿Qué libro del AT NO se encontró representado en Qumrán?","Génesis","Ester","Jeremías","Job",1,"Ester es el único libro del AT sin representación en Qumrán"],
["¿Cuántos capítulos tiene el libro de Amós?","7","8","9","10",2,"9 capítulos"],
["¿Cuántos capítulos tiene el libro de Miqueas?","5","6","7","8",2,"7 capítulos"],
["¿De qué ciudad era originario el profeta Amós?","Tekoa","Belén","Hebrón","Nazaret",0,"Amós 1,1 — Tekoa, en Judá"],
["¿En qué reino predicó Amós aunque era del Reino del Sur?","Judá","Israel del Norte","Babilonia","Egipto",1,"Amós predicó en el Norte, especialmente en Betel (Am 7,10)"],
["¿Qué profesión tenía Amós antes de ser profeta?","Sacerdote","Pescador","Pastor y cultivador de sicomoros","Escriba",2,"Amós 1,1; 7,14 — pastor y cultivador de sicomoros"],
["¿Cuántos capítulos tiene el libro de Oseas?","12","13","14","15",2,"14 capítulos"],
["¿Cuántos capítulos tiene el libro de Zacarías?","12","13","14","15",2,"14 capítulos"],
["¿Cuántos capítulos tiene el libro de Malaquías?","2","3","4","5",2,"4 capítulos — el último del AT"],
["¿Cuántos capítulos tiene el libro de Abdías?","1","2","3","4",0,"Abdías — 1 capítulo, 21 versículos"],
["¿Cuántos capítulos tiene el libro de Nahúm?","2","3","4","5",1,"3 capítulos"],
["¿Cuántos capítulos tiene el libro de Habacuc?","2","3","4","5",1,"3 capítulos"],
["¿Cuántos capítulos tiene el libro de Sofonías?","2","3","4","5",1,"3 capítulos"],
["¿Cuántos capítulos tiene el libro de Hageo?","1","2","3","4",1,"2 capítulos"],
["¿Cuántos capítulos tiene el libro de Joel?","2","3","4","5",1,"3 capítulos (en la LXX tiene 4)"],
["¿Cuántos capítulos tiene el libro de Jonás?","3","4","5","6",1,"4 capítulos"],
["¿Qué tiene de especial la oración de Jonás en el vientre del pez?","Es una lamentación original","Es un salmo tomado de la tradición (Sal 18, 31, etc.)","Es una profecía","Es un himno de alabanza nuevo",1,"Jonás 2,3-10 — es un salmo de acción de gracias compuesto con referencias a otros salmos"],
["¿De dónde huyó Jonás cuando Dios le ordenó ir a Nínive?","De Jerusalén hacia el desierto","De Jope hacia Tarsis (España)","De Samaria hacia Egipto","De Damasco hacia Persia",1,"Jonás 1,3 — embarcó en Jope rumbo a Tarsis"],
["¿Cuál era la capital del Imperio Asirio que debía visitar Jonás?","Babilonia","Damasco","Nínive","Ur",2,"Jonás 1,2 — Nínive"],
["¿Cuántos días de camino tenía Nínive según el libro de Jonás?","1","2","3","7",2,"Jonás 3,3 — 'ciudad de tres días de camino'"],
["¿Quién fue el primer profeta bíblico enviado explícitamente a los paganos?","Elías","Eliseo","Amós","Jonás",3,"Jonás — enviado a Nínive, ciudad gentil"],
["¿Cuántos capítulos tiene el libro de Rut?","3","4","5","6",1,"4 capítulos"],
["¿Cuántos capítulos tiene el libro de Judit?","14","15","16","17",2,"16 capítulos"],
["¿Cuántos capítulos tiene el libro de Tobías?","13","14","15","16",1,"14 capítulos (o 13 en algunas versiones)"],
["¿Cuántos capítulos tiene el libro del Sirácida?","48","50","51","52",2,"51 capítulos"],
["¿Cuántos capítulos tiene el libro de la Sabiduría?","17","18","19","20",2,"19 capítulos"],
["¿Cuántos capítulos tiene el libro de Baruc?","5","6","7","8",1,"6 capítulos (incluyendo la Carta de Jeremías como cap. 6)"],
["¿Cuántos capítulos tiene el Primer Libro de los Macabeos?","14","15","16","17",2,"16 capítulos"],
["¿Cuántos capítulos tiene el Segundo Libro de los Macabeos?","13","14","15","16",2,"15 capítulos"],
["¿Qué fiesta judía conmemora la purificación del Templo profanado por Antíoco IV?","El Yom Kipur","La Pascua","Purim","Jánuca (Hanukkah)",3,"1 Macabeos 4,59 — Jánuca, la fiesta de la Dedicación"],
["¿Qué fiesta judía conmemora la salvación de los judíos en tiempos de Ester?","Jánuca","Yom Kipur","Purim","Sukkot",2,"Ester 9,28 — Purim"],
["¿Cuántos capítulos tiene el libro de Ester?","8","9","10","12",2,"10 capítulos (en hebreo); las adiciones griegas amplían el libro"],
["¿Cuántos versículos tiene el libro de Ester en la versión griega (LXX)?","177","270","339","400",1,"270 versículos en la LXX de Ester (vs. 167 en hebreo)"],
["¿Cuántos capítulos tiene el libro de Esdras?","8","9","10","12",2,"10 capítulos"],
["¿Cuántos capítulos tiene el libro de Nehemías?","11","12","13","14",2,"13 capítulos"],
["¿Cuántos capítulos tienen los dos libros de las Crónicas juntos?","52","54","55","65",3,"1Cr (29) + 2Cr (36) = 65 capítulos"],
["¿En qué libro del AT hay listas de los guardas del arca y de los músicos del Templo?","1 y 2 Reyes","1 y 2 Crónicas","Esdras","Nehemías",1,"1 Crónicas 15-16 — los levitas músicos"],
["¿Quién fue Qohélet en el marco literario del Eclesiastés?","El rey Salomón bajo pseudónimo","Un sabio anónimo","El profeta Isaías","Un sumo sacerdote",0,"Qohélet se presenta como 'hijo de David, rey de Jerusalén'"],
["¿Cuántos versículos tiene el libro de Abdías?","15","19","21","25",2,"21 versículos — el libro más corto del AT"],
["¿Contra qué nación es el oráculo de Abdías?","Babilonia","Asiria","Edom","Moab",2,"Abdías 1 — oráculo contra Edom"],
["¿Qué región del mundo antiguo era Edom?","Al norte de Israel","Al este del Jordán","Al sur de Judá (actual Jordania meridional)","Al oeste, junto al Mediterráneo",2,"Edom estaba al sur de Judá y este del Arabá"],
["¿Cuántos capítulos tiene el Primer libro de Samuel?","29","30","31","32",2,"31 capítulos"],
["¿Cuántos capítulos tiene el Segundo libro de Samuel?","22","23","24","25",2,"24 capítulos"],
["¿Cuántos capítulos tiene el Primer libro de los Reyes?","20","21","22","23",2,"22 capítulos"],
["¿Cuántos capítulos tiene el Segundo libro de los Reyes?","23","24","25","26",2,"25 capítulos"],
["¿Cuántos capítulos tiene el libro de los Jueces?","19","20","21","22",2,"21 capítulos"],
["¿Cuántos capítulos tiene el libro de Josué?","22","23","24","25",2,"24 capítulos"],
["¿Qué significa 'Éxodo'?","El pueblo de Dios","La ley","La salida","El pacto",2,"Del griego ἔξοδος — 'la salida'"],
["¿Qué significa 'Levítico'?","El libro de los sacerdotes","El libro de las leyes","El libro de los levitas","El libro de los sacrificios",2,"Del latín Leviticus — relativo a los levitas"],
["¿Qué significa 'Números' como nombre del libro bíblico?","El libro de las cifras","El libro del censo (de los 'contados')","El libro de los números sagrados","El libro de los días",1,"Del latín Numeri — por el censo que hay en él"],
["¿Qué significa 'Deuteronomio'?","Segunda ley / repetición de la ley","El quinto libro","La ley final","El libro del desierto",0,"Del griego Δευτερονόμιον — 'segunda ley'"],
["¿Qué profeta fue llevado en una visión al Templo de Jerusalén a 600 km de Babilonia?","Isaías","Jeremías","Daniel","Ezequiel",3,"Ezequiel 8 — visión del Templo mientras está en Babilonia"],
["¿Qué tipo de literatura es el libro del Apocalipsis?","Profecía clásica","Historia","Epistolar","Apocalíptica",3,"Apocalipsis — género apocalíptico judeo-cristiano"],
["¿Cuál fue el contexto histórico del libro del Apocalipsis?","Persecución bajo Nerón","Persecución bajo Domiciano (81-96 d.C.)","El exilio en Babilonia","La guerra del 66-70 d.C.",1,"Apocalipsis fue escrito ca. 95 d.C., bajo Domiciano"],
["¿Qué isla estaba exiliado Juan cuando escribió el Apocalipsis?","Malta","Chipre","Creta","Patmos",3,"Apocalipsis 1,9 — Juan en Patmos"],
["¿Cuál fue el primer concilio ecuménico que definió el canon del NT?","Nicea (325)","Éfeso (431)","Cartago (397) y luego Trento (1546)","Calcedonia (451)",2,"Concilios de Hipona (393) y Cartago (397) y definitivamente Trento (1546)"],
["¿En qué año fue fijado el canon del AT en el judaísmo (llamado Sínodo de Jamnia)?","70 d.C.","90 d.C.","100 d.C.","120 d.C.",1,"Ca. 90 d.C. — aunque hoy se cuestiona que fuera un 'concilio'"],
["¿Qué fue el 'Sínodo de Jamnia'?","Un concilio donde se definió el canon hebreo del AT","Un concilio sobre la liturgia judía","Una reunión de fariseos sobre la ley","Una disputa entre saduceos y fariseos",0,"Ca. 90 d.C. — los rabinos discutieron el canon, especialmente Cantar y Eclesiastés"],
["¿Quién fue el principal rabino que encabezó la academia de Jamnia?","Hillel","Shammai","Rabán Gamaliel II","Akivá",2,"Rabán Gamaliel II presidió la academia de Yavné (Jamnia)"],
["¿Cuántos manuscritos griegos del NT existen?","2000","5000+","8000","10000",1,"Más de 5000 manuscritos griegos del NT"],
["¿Cuál es el manuscrito más antiguo y completo del NT?","Papiro P52","Códice Sinaítico","Códice Vaticano","Códice Alejandrino",1,"El Códice Sinaítico (siglo IV) es el más antiguo casi completo del NT"],
["¿Cuál es el papiro más antiguo del NT (con texto de Juan 18)?","P45","P46","P52","P66",2,"P52 — ca. 125-175 d.C., con Jn 18,31-33.37-38"],
["¿En qué siglo d.C. data el Códice Sinaítico?","Siglo III","Siglo IV","Siglo V","Siglo VI",1,"Siglo IV d.C. — descubierto por Tischendorf en el Sinaí"],
["¿Quién descubrió el Códice Sinaítico en el monasterio de Santa Catalina?","Erasmo","Tischendorf","Westcott","Hort",1,"Constantin von Tischendorf, 1844/1859"],
["¿Qué idioma usó Jesús para citar el Salmo 22 desde la cruz?","Hebreo","Griego","Latín","Arameo",3,"Marcos 15,34 — 'Eloi, Eloi, lama sabachtani' en arameo"],
["¿Qué lengua dominante unificó el mundo mediterráneo en tiempos del NT?","El latín","El griego koiné","El arameo","El hebreo",1,"El griego koiné — la lingua franca del Imperio Romano oriental"],
["¿Qué significa 'koiné' en el contexto del griego del NT?","Griego clásico","Griego común / popular","Griego bíblico","Griego culto",1,"Κοινή — 'común', el griego popular helenístico"],
["¿Qué es el 'Textus Receptus'?","El texto griego del NT de Erasmo, base de las traducciones protestantes del siglo XVI","El texto latino de la Vulgata","El texto oficial católico del NT","El texto de los rollos del Mar Muerto",0,"El Textus Receptus de Erasmo (1516) y Beza — base de la KJV"],
["¿Qué es la 'crítica textual' bíblica?","Un estudio que niega la inspiración","La ciencia que establece el texto original comparando manuscritos","Un método de interpretación filosófica","El análisis histórico de los autores",1,"Textual criticism — reconstruir el texto original a partir de manuscritos"],
["¿Cuántos versículos tiene el Evangelio de Marcos según el texto más antiguo (sin el final largo)?","16,1-8","16,1-14","16,1-20","16,1-18",0,"Marcos 16,1-8 — el final largo (16,9-20) es un añadido posterior"],
["¿Cuántos versículos del final largo de Marcos (16,9-20) son considerados añadidos posteriores?","5","8","12","20",2,"Marcos 16,9-20 — 12 versículos del final largo son un añadido"],
["¿Qué sección del Evangelio de Juan es considerada un añadido posterior?","Juan 7,53-8,11","Juan 6,51-58","Juan 11,1-44","Juan 20,30-31",0,"Juan 7,53-8,11 — la perícopa de la mujer adúltera"],
["¿Qué versículo de 1 Juan 5 fue añadido en algunos manuscritos tardíos y no está en los más antiguos?","1 Jn 5,6","1 Jn 5,7 (Comma Johanneum)","1 Jn 5,9","1 Jn 5,13",1,"El Comma Johanneum (1 Jn 5,7) — no está en los manuscritos griegos más antiguos"],
["¿Qué es el 'Comma Johanneum'?","Un signo de puntuación hebreo","Un versículo sobre la Trinidad añadido en 1 Jn 5,7 por tradición latina","Un salmo litúrgico","Un texto de Qumrán",1,"1 Juan 5,7 — 'el Padre, el Verbo y el Espíritu Santo' — texto tardío"],
["¿Cuántas pericopes aductorae (textos añadidos) se reconocen en el NT?","1","2","3","4",1,"Las dos más importantes: Mc 16,9-20 y Jn 7,53-8,11"],
["¿Cuántas fuentes usó Lucas para escribir su evangelio según Lc 1,1-4?","Solo Marcos","Solo testimonios orales","Diversas fuentes escritas y testimonios oculares","Solo su propia investigación",2,"Lucas 1,1-4 — 'muchos se propusieron narrar...'"],
["¿Qué es la fuente 'Q' en los estudios del NT?","El Evangelio de Juan","Un hipotético documento de dichos de Jesús usado por Mateo y Lucas","El Evangelio de Marcos","Los dichos de Pablo",1,"Q = Quelle (fuente en alemán) — dichos comunes a Mateo y Lucas"],
["¿Cuántos versículos se atribuyen aproximadamente a la fuente Q?","100","200","235","350",2,"Ca. 235 versículos de 'dichos' de Jesús"],
["¿Cuál es el orden cronológico de los evangelios según el consenso mayoritario?","Mateo, Marcos, Lucas, Juan","Marcos, Mateo, Lucas, Juan","Lucas, Mateo, Marcos, Juan","Juan, Marcos, Mateo, Lucas",1,"Marcos (ca. 65-70), Mateo y Lucas (ca. 80-90), Juan (ca. 90-100)"],
["¿En qué año aproximado fue escrito el Evangelio de Marcos?","50 d.C.","65-70 d.C.","80 d.C.","90 d.C.",1,"Marcos ca. 65-70 d.C. — antes o durante la guerra judía"],
["¿En qué año aproximado fue escrito el Evangelio de Juan?","70 d.C.","80 d.C.","90-100 d.C.","110 d.C.",2,"Juan ca. 90-100 d.C. — el más tardío de los evangelios"],
["¿En qué ciudad se cree que fue escrito el Evangelio de Marcos?","Antioquía","Éfeso","Alejandría","Roma",3,"Según la tradición, Marcos escribió en Roma"],
["¿En qué ciudad se cree que fue escrito el Evangelio de Juan?","Roma","Alejandría","Antioquía","Éfeso",3,"Según la tradición, Juan escribió en Éfeso"],
["¿Qué es el 'Evangelio de los Hebreos'?","Otro nombre para Mateo","Un evangelio apócrifo judeo-cristiano citado por los Padres","Un evangelio gnóstico","El evangelio de la comunidad de Qumrán",1,"El Evangelio de los Hebreos — apócrifo judeo-cristiano"],
["¿Cuántos evangelios apócrifos reconoce la tradición?","5","10","Más de 20","Solo 2",2,"Más de 20 evangelios apócrifos conocidos: Tomás, Pedro, Felipe, etc."],
["¿Qué es el Evangelio de Tomás?","Un evangelio sinóptico tardío","Una colección de 114 dichos de Jesús, sin relatos","Una gnosis cristiana completa","El 5° evangelio apócrifo más corto",1,"El Evangelio de Tomás — 114 logia (dichos) de Jesús"],
["¿En qué idioma fue encontrado el Evangelio de Tomás?","Griego","Arameo","Copto","Latín",2,"Los códices de Nag Hammadi (1945) están en copto"],
["¿Dónde se encontraron los códices de Nag Hammadi?","Qumrán","Alejandría","Nag Hammadi, Egipto","El Cairo",2,"Nag Hammadi, Alto Egipto, 1945"],
["¿En qué año se encontraron los textos de Nag Hammadi?","1945","1947","1950","1955",0,"1945 — dos años antes de los rollos del Mar Muerto"],
["¿Qué tipo de textos son los de Nag Hammadi?","Escritos esenios","Cartas de Pablo desconocidas","Textos gnósticos cristiano-egipcios","Comentarios rabínicos",2,"Textos gnósticos del siglo II-IV d.C., en copto"],
["¿Cuántos textos (códices) se encontraron en Nag Hammadi?","10","13","16","20",1,"13 códices con 52 textos en Nag Hammadi"],
["¿En qué siglo vivió Pablo?","Siglo I a.C.","Siglo I d.C.","Siglo II d.C.","Siglo I a.C. - I d.C.",1,"Pablo: ca. 5-10 d.C. - ca. 64-67 d.C."],
["¿En qué ciudad nació Pablo?","Jerusalén","Roma","Éfeso","Tarso de Cilicia",3,"Hechos 9,11; 22,3 — Tarso de Cilicia"],
["¿Qué ciudadanía tenía Pablo?","Solo judía","Solo romana","Judía y romana","Griega y romana",2,"Hechos 22,25-28 — ciudadano romano de nacimiento"],
["¿Ante quién estudió Pablo en Jerusalén?","El sacerdote Ananás","El sumo sacerdote Caifás","Gamaliel el Elder","Hillel el Anciano",2,"Hechos 22,3 — a los pies de Gamaliel"],
["¿Qué fue Pablo antes de convertirse?","Un zelote","Un saduceo","Un fariseo","Un esenio",2,"Hechos 23,6; Filipenses 3,5 — fariseo de los fariseos"],
["¿De qué tribu de Israel era Pablo?","Judá","Leví","Benjamín","Efraín",2,"Filipenses 3,5; Romanos 11,1 — de la tribu de Benjamín"],
["¿Dónde murió Pablo según la tradición?","Éfeso","Corinto","Antioquía","Roma",3,"Tradición cristiana — martirio en Roma bajo Nerón"],
["¿Dónde murió Pedro según la tradición?","Antioquía","Éfeso","Roma","Corinto",2,"Tradición cristiana — crucificado en Roma bajo Nerón"],
["¿Cómo fue la muerte de Pedro según la tradición?","Decapitado","Ahorcado","Crucificado boca abajo","Apedreado",2,"Tradición: Pedro pidió ser crucificado boca abajo por humildad"],
["¿Cuántos capítulos tiene la carta a los Filipenses?","3","4","5","6",1,"4 capítulos"],
["¿Cuántos capítulos tiene la carta a los Colosenses?","3","4","5","6",1,"4 capítulos"],
["¿Cuántos capítulos tiene la Primera carta a los Corintios?","14","15","16","17",2,"16 capítulos"],
["¿Cuántos capítulos tiene la Segunda carta a los Corintios?","12","13","14","15",1,"13 capítulos"],
["¿Cuántos capítulos tiene la carta a los Gálatas?","5","6","7","8",1,"6 capítulos"],
["¿Cuántos capítulos tiene la Primera carta a los Tesalonicenses?","4","5","6","7",1,"5 capítulos"],
["¿Cuántos capítulos tiene la Segunda carta a los Tesalonicenses?","2","3","4","5",1,"3 capítulos"],
["¿Cuántos capítulos tiene la Primera carta a Timoteo?","5","6","7","8",1,"6 capítulos"],
["¿Cuántos capítulos tiene la Segunda carta a Timoteo?","3","4","5","6",1,"4 capítulos"],
["¿Cuántos capítulos tiene la carta a Tito?","2","3","4","5",1,"3 capítulos"],
["¿Cuántos capítulos tiene la carta a Filemón?","1","2","3","4",0,"1 capítulo — 25 versículos"],
["¿Cuántos capítulos tiene la carta a los Hebreos?","12","13","14","15",1,"13 capítulos"],
["¿Cuántos capítulos tiene la carta de Santiago?","4","5","6","7",1,"5 capítulos"],
["¿Cuántos capítulos tiene la Primera carta de Pedro?","4","5","6","7",1,"5 capítulos"],
["¿Cuántos capítulos tiene la Segunda carta de Pedro?","2","3","4","5",1,"3 capítulos"],
["¿Cuántos capítulos tiene la Primera carta de Juan?","4","5","6","7",1,"5 capítulos"],
["¿Cuántos versículos tiene la carta a Filemón?","20","25","30","35",1,"25 versículos"],
["¿Cuántos versículos tiene la Segunda carta de Juan?","10","13","15","18",1,"13 versículos"],
["¿Cuántos versículos tiene la Tercera carta de Juan?","14","15","16","17",0,"14 versículos"],
["¿Cuántos versículos tiene la carta de Judas?","22","24","25","27",2,"25 versículos"],
["¿En qué libro del NT aparece el himno al Logos?","Mateo 1","Marcos 1","Lucas 1","Juan 1",3,"Juan 1,1-18 — el prólogo del Evangelio de Juan"],
["¿Cuántos versículos tiene el Prólogo del Evangelio de Juan?","16","17","18","19",2,"18 versículos (Juan 1,1-18)"],
["¿En qué versículo de Juan dice 'Dios nadie lo ha visto jamás'?","Juan 1,1","Juan 1,14","Juan 1,18","Juan 3,16",2,"Juan 1,18 — θεὸν οὐδεὶς ἑώρακεν πώποτε"],
["¿Qué nombre arameo usó Jesús para Dios en la oración del huerto?","Adonai","Elohim","Yahvé","Abba",3,"Marcos 14,36 — Ἀββᾶ ὁ πατήρ"],
["¿Cuántos capítulos tiene la Segunda carta de Juan?","1","2","3","4",0,"2 Juan — 1 capítulo, 13 versículos"],
["¿Cuántos capítulos tiene la Tercera carta de Juan?","1","2","3","4",0,"3 Juan — 1 capítulo, 14 versículos"],
["¿Cuántos capítulos tiene la carta de Judas?","1","2","3","4",0,"Judas — 1 capítulo, 25 versículos"],
["¿En qué versículo dice Pablo 'Ya no soy yo quien vive, sino Cristo que vive en mí'?","Gálatas 2,16","Gálatas 2,20","Filipenses 1,21","Romanos 8,10",1,"Gálatas 2,20"],
["¿En qué versículo dice Pablo 'Para mí vivir es Cristo y morir una ganancia'?","Gálatas 2,20","1 Co 15,31","Filipenses 1,21","Romanos 14,8",2,"Filipenses 1,21"],
["¿En qué versículo Pablo dice 'Todo lo puedo en aquel que me da fuerzas'?","Romanos 8,28","Efesios 6,10","Filipenses 4,13","Colosenses 1,29",2,"Filipenses 4,13"],
["¿En qué versículo dice Pablo 'Dios coopera en todo para el bien de los que le aman'?","Romanos 5,5","Romanos 8,28","Filipenses 4,7","1 Corintios 10,13",1,"Romanos 8,28"],
["¿Cuántos capítulos tiene el libro de los Proverbios?","28","29","30","31",3,"31 capítulos"],
["¿Cuántos capítulos tiene el libro de Job?","40","41","42","43",2,"42 capítulos"],
["¿Cuántos capítulos tiene el libro de los Salmos?","148","149","150","151",2,"150 Salmos = 150 capítulos"]
];
raw.forEach(function(r){
    allQuestions.push({question:r[0],options:[r[1],r[2],r[3],r[4]],answer:r[5],difficulty:4,money:5000,isSafeHaven:false,source:r[6]});
});
})();
