// bank1.js - Nivel 1: Debutante (200 preguntas)
(function() {
var raw = [
// [pregunta, A, B, C, D, respuesta(0-3), fuente]
["¿Quién construyó el arca para salvarse del diluvio?","Moisés","Noé","Abraham","David",1,"Génesis 6,14"],
["¿En qué ciudad nació Jesús?","Nazaret","Jerusalén","Belén","Cafarnaúm",2,"Lucas 2,4-7"],
["¿Cuántos apóstoles eligió Jesús?","10","7","12","70",2,"Marcos 3,13-14"],
["¿Quién bautizó a Jesús?","Pedro","Pablo","Juan el Bautista","Elías",2,"Mateo 3,13-17"],
["¿Con qué venció David a Goliat?","Espada","Honda y piedra","Lanza","Arco y flecha",1,"1 Samuel 17,50"],
["¿Cuántos libros tiene la Biblia católica?","66","72","73","77",2,"Canon bíblico católico"],
["¿Cómo se llama el jardín donde vivían Adán y Eva?","Getsemaní","Edén","Galilea","Sinaí",1,"Génesis 2,8"],
["¿Quién fue el primer hombre creado por Dios?","Abel","Caín","Adán","Noé",2,"Génesis 2,7"],
["¿Cuántos días duró el diluvio en tiempos de Noé?","7 días","30 días","40 días y noches","100 días",2,"Génesis 7,17"],
["¿Qué señal puso Dios en el cielo tras el diluvio?","Una estrella","Un arcoíris","Una nube","El sol",1,"Génesis 9,13"],
["¿Cuántos mandamientos recibió Moisés en el Sinaí?","5","7","10","12",2,"Éxodo 20,1-17"],
["¿Qué mar cruzó Moisés con los israelitas?","Mar Mediterráneo","Mar Muerto","Mar Rojo","Mar de Galilea",2,"Éxodo 14,21"],
["¿A través de qué signo habló Dios a Moisés en el desierto?","Un ángel visible","Una paloma","Una zarza ardiente","Un cordero",2,"Éxodo 3,2"],
["¿Quién mató a Abel?","Adán","Noé","Caín","Set",2,"Génesis 4,8"],
["¿Cuántos hijos tuvo Jacob?","10","11","12","13",2,"Génesis 35,22-26"],
["¿Cuál es el salmo que comienza 'El Señor es mi pastor'?","Salmo 1","Salmo 23","Salmo 51","Salmo 100",1,"Salmo 23,1"],
["¿A qué profeta tragó un gran pez?","Elías","Isaías","Jonás","Daniel",2,"Jonás 2,1"],
["¿Cuántos días estuvo Jonás dentro del gran pez?","1","3","7","40",1,"Jonás 2,1"],
["¿A quién se atribuyen la mayoría de los Salmos?","Salomón","David","Moisés","Asaf",1,"Títulos de los Salmos"],
["¿Cuál es el libro más largo de la Biblia?","Isaías","Génesis","Salmos","Mateo",2,"Salmos tiene 150 capítulos"],
["¿Quién fue el primer rey de Israel?","David","Saúl","Salomón","Roboam",1,"1 Samuel 10,24"],
["¿Qué construyó Salomón en Jerusalén?","Un palacio","El Templo","Una fortaleza","Una escuela",1,"1 Reyes 6,1"],
["¿Cuánto tiempo estuvo Jesús en el desierto siendo tentado?","7 días","20 días","40 días","30 días",2,"Mateo 4,2"],
["¿Quién traicionó a Jesús?","Pedro","Judas","Tomás","Marcos",1,"Mateo 26,14-16"],
["¿Cuántas monedas de plata recibió Judas por traicionar a Jesús?","10","30","50","100",1,"Mateo 26,15"],
["¿Cómo se llamaba el lugar donde crucificaron a Jesús?","Getsemaní","Belén","Gólgota","Sinaí",2,"Mateo 27,33"],
["¿Quién ayudó a Jesús a cargar la cruz?","Juan","Simón de Cirene","Pedro","Zaqueo",1,"Lucas 23,26"],
["¿Al tercer día después de morir, qué hizo Jesús?","Ascendió al cielo","Apareció a los apóstoles","Resucitó","Habló con María",2,"1 Corintios 15,4"],
["¿Quién fue la primera en ver a Jesús resucitado según Juan?","Pedro","María Magdalena","Juan","Santiago",1,"Juan 20,14-16"],
["¿Cómo se llamaba la madre de Jesús?","Ana","María","Marta","Elizabet",1,"Lucas 1,26-27"],
["¿Quién era el padre adoptivo de Jesús?","Zacarías","Simeón","José","Joaquín",2,"Mateo 1,16"],
["¿Qué oficio tenía José, esposo de María?","Pescador","Carpintero","Pastor","Comerciante",1,"Mateo 13,55"],
["¿En qué pueblo de Galilea creció Jesús?","Belén","Cafarnaúm","Nazaret","Caná",2,"Lucas 2,51"],
["¿Cuál fue el primer milagro de Jesús?","Curar un ciego","Multiplicar panes","Convertir agua en vino","Resucitar a Lázaro",2,"Juan 2,1-11"],
["¿En qué ciudad realizó Jesús su primer milagro?","Belén","Caná de Galilea","Nazaret","Jerusalén",1,"Juan 2,1"],
["¿Qué multiplicó Jesús para alimentar a la multitud?","Agua y vino","Pan y peces","Carne y pan","Fruta y pan",1,"Mateo 14,19-21"],
["¿Con cuántos panes y peces alimentó Jesús a los 5000?","5 panes y 2 peces","7 panes y 3 peces","3 panes y 5 peces","2 panes y 7 peces",0,"Mateo 14,17-21"],
["¿Sobre qué caminó Jesús para ir al encuentro de sus discípulos?","El barro","El agua","Las nubes","La tierra",1,"Mateo 14,25"],
["¿A quién resucitó Jesús en Betania?","Jairo","Tabita","Lázaro","El hijo de la viuda",2,"Juan 11,43-44"],
["¿Cuántos días llevaba Lázaro muerto cuando Jesús lo resucitó?","1","2","3","4",3,"Juan 11,39"],
["¿Cuál fue el mandamiento más importante según Jesús?","Honrar a los padres","Amar a Dios y al prójimo","No matar","Guardar el sábado",1,"Mateo 22,37-39"],
["¿Con qué palabras comenzó Jesús el Padrenuestro?","Padre eterno","Padre nuestro que estás en los cielos","Oh Dios todopoderoso","Señor, escúchanos",1,"Mateo 6,9"],
["¿Cuántas bienaventuranzas proclamó Jesús en el Sermón del Monte?","7","8","10","12",1,"Mateo 5,3-10"],
["¿Dónde predicó Jesús el Sermón del Monte?","En el templo","En una sinagoga","En una montaña","En el río Jordán",2,"Mateo 5,1"],
["¿A quién dijo Jesús 'Tú eres Pedro, y sobre esta piedra edificaré mi Iglesia'?","A Juan","A Simón, llamado Pedro","A Santiago","A Andrés",1,"Mateo 16,18"],
["¿Cómo se llamaba el recaudador de impuestos que se convirtió en apóstol?","Nicodemo","Zaqueo","Mateo","Bartolomé",2,"Mateo 9,9"],
["¿Quién era Zaqueo?","Un pescador","Un recaudador de impuestos","Un fariseo","Un sacerdote",1,"Lucas 19,2"],
["¿En qué ciudad vivía Zaqueo?","Jerusalén","Jericó","Nazaret","Cafarnaúm",1,"Lucas 19,1"],
["¿Por qué se subió Zaqueo a un árbol?","Para ver mejor a Jesús","Para escapar de la multitud","Para descansar","Por costumbre",0,"Lucas 19,4"],
["¿A qué tipo de árbol se subió Zaqueo?","Un olivo","Una palmera","Un sicómoro","Un cedro",2,"Lucas 19,4"],
["¿Cuántos hijos tenía el padre en la parábola del hijo pródigo?","1","2","3","4",1,"Lucas 15,11"],
["¿Cuántas ovejas tenía el pastor en la parábola de la oveja perdida?","10","50","100","1000",2,"Lucas 15,4"],
["¿Cuántas monedas tenía la mujer en la parábola de la moneda perdida?","5","7","10","12",2,"Lucas 15,8"],
["¿Qué hace el sembrador en la parábola del sembrador?","Siembra semilla","Recoge cosecha","Planta árboles","Riega el campo",0,"Mateo 13,3"],
["¿En qué libro está la historia de Abraham?","Éxodo","Levítico","Génesis","Números",2,"Génesis 12-25"],
["¿Quién fue el hijo de Abraham y Sara?","José","Ismael","Isaac","Lot",2,"Génesis 21,3"],
["¿A qué montaña llevó Abraham a Isaac para sacrificarlo?","Sinaí","Tabor","Moria","Carmelo",2,"Génesis 22,2"],
["¿Qué detuvo a Abraham cuando iba a sacrificar a Isaac?","Un terremoto","El llanto de Isaac","El ángel del Señor","Sara",2,"Génesis 22,11-12"],
["¿Qué animal encontró Abraham para ofrecer en lugar de Isaac?","Un cordero","Un toro","Un carnero","Una oveja",2,"Génesis 22,13"],
["¿Cómo se llamó el hijo de Isaac que se convirtió en patriarca?","Esaú","Ismael","José","Jacob",3,"Génesis 25,26"],
["¿Por qué fue vendido José como esclavo por sus hermanos?","Por robar","Por envidia","Se fugó de casa","Por orden del faraón",1,"Génesis 37,11"],
["¿A qué país fue vendido José como esclavo?","Babilonia","Egipto","Asiria","Canaán",1,"Génesis 37,36"],
["¿Qué don especial tenía José, hijo de Jacob?","Curar enfermos","Hablar con animales","Interpretar sueños","Ver el futuro directamente",2,"Génesis 40-41"],
["¿Quién encontró a Moisés flotando en el Nilo siendo bebé?","Una sirvienta","La hija del faraón","Su hermana Miriam","Una sacerdotisa",1,"Éxodo 2,5-6"],
["¿Cómo escapó Moisés de ser asesinado de niño?","En una canasta en el río Nilo","Escondido en el desierto","En una cueva","Bajo el cuidado de un pastor",0,"Éxodo 2,3"],
["¿Cuántas plagas envió Dios sobre Egipto?","7","9","10","12",2,"Éxodo 7-12"],
["¿Cuál fue la décima plaga de Egipto?","La oscuridad","Las langostas","Los piojos","La muerte de los primogénitos",3,"Éxodo 11,5"],
["¿Qué celebración recuerda la liberación de Egipto?","La Navidad","La Pascua","Pentecostés","El Yom Kipur",1,"Éxodo 12,14"],
["¿Qué enviaba Dios como alimento a los israelitas en el desierto?","Pan del cielo (maná)","Carne asada","Fruta de árboles","Agua y leche",0,"Éxodo 16,31"],
["¿Cuántos años anduvieron los israelitas por el desierto?","20","40","30","50",1,"Números 14,33"],
["¿Quién sucedió a Moisés como líder de Israel?","Caleb","Eleazar","Finees","Josué",3,"Deuteronomio 31,7-8"],
["¿Qué río cruzaron los israelitas para entrar a Canaán?","El Nilo","El Éufrates","El Jordán","El Tigris",2,"Josué 3,17"],
["¿Cómo cayeron las murallas de Jericó?","Con un terremoto","Con catapultas","Dando vueltas y tocando trompetas","Con la lluvia",2,"Josué 6,20"],
["¿Quién fue la jueza y profetisa de Israel?","Raquel","Débora","Ana","Rut",1,"Jueces 4,4"],
["¿Cuál era la fuente de fuerza de Sansón?","Sus músculos","Su fe","Su cabello","Una espada especial",2,"Jueces 16,17"],
["¿Quién cortó el cabello de Sansón?","Dalila","Raquel","Mical","Betsabé",0,"Jueces 16,19"],
["¿A dónde fue Rut con su suegra Noemí?","Egipto","Babilonia","Belén","Moab",2,"Rut 1,19"],
["¿Quién fue el esposo de Rut al final del libro?","David","Booz","Elimélec","Jonatán",1,"Rut 4,13"],
["¿Cómo se llamaba la madre de Samuel?","Noemí","Débora","Raquel","Ana",3,"1 Samuel 1,20"],
["¿Quién ungió a David como rey?","Moisés","Josué","Samuel","Elías",2,"1 Samuel 16,13"],
["¿Cuántos años reinó David sobre Israel?","20","30","40","50",2,"2 Samuel 5,4"],
["¿Por qué era famoso Salomón?","Por su riqueza","Por su valentía","Por su sabiduría","Por su belleza",2,"1 Reyes 3,12"],
["¿Quién fue el profeta que enfrentó a los 450 profetas de Baal?","Eliseo","Isaías","Jeremías","Elías",3,"1 Reyes 18,19"],
["¿Cómo fue llevado al cielo el profeta Elías?","En una nube","Por ángeles","Caminando tranquilamente","En un torbellino con carro de fuego",3,"2 Reyes 2,11"],
["¿Quién fue el sucesor del profeta Elías?","Isaías","Jeremías","Ezequiel","Eliseo",3,"1 Reyes 19,16"],
["¿En qué foso fue arrojado Daniel por orar a Dios?","Un pozo de agua","Una cisterna","Una fosa de leones","Un horno de fuego",2,"Daniel 6,17"],
["¿Cuántos jóvenes hebreos fueron arrojados al horno encendido en Babilonia?","1","2","3","4",2,"Daniel 3,20-23"],
["¿En qué libro se narra la historia del horno de fuego?","Éxodo","Génesis","Daniel","Isaías",2,"Daniel 3"],
["¿Cuántos días tardó Dios en crear el mundo según el Génesis?","5","6","7","8",1,"Génesis 1,31-2,2"],
["¿Qué creó Dios el primer día?","La luz","El sol","Las estrellas","La luna",0,"Génesis 1,3"],
["¿Cuándo descansó Dios de su obra creadora?","El quinto día","El sexto día","El séptimo día","El octavo día",2,"Génesis 2,2"],
["¿De qué material formó Dios al hombre?","Agua","Barro (polvo de la tierra)","Piedra","Madera",1,"Génesis 2,7"],
["¿De qué parte del cuerpo de Adán formó Dios a Eva?","Brazo","Pierna","Cabeza","Costilla",3,"Génesis 2,21-22"],
["¿Quién tentó a Eva en el jardín?","La serpiente","El ángel","Adán","Dios mismo",0,"Génesis 3,1"],
["¿Cuántos hijos tenía Noé?","2","3","4","5",1,"Génesis 6,10 — Sem, Cam, Jafet"],
["¿En qué montaña se posó el arca de Noé?","Sinaí","Tabor","Ararat","Carmelo",2,"Génesis 8,4"],
["¿Qué ave envió Noé primero del arca?","Una paloma","Un cuervo","Una golondrina","Un águila",1,"Génesis 8,7"],
["¿Qué trajo la paloma de regreso al arca?","Una hoja de higuera","Una rama de olivo","Una flor","Nada",1,"Génesis 8,11"],
["¿Cómo se llamaba el padre de Abraham?","Noé","Sem","Eber","Taré",3,"Génesis 11,26"],
["¿Cómo se llamaba Abraham antes de que Dios cambiara su nombre?","Abel","Abram","Abner","Absalón",1,"Génesis 17,5"],
["¿De qué ciudad salió Abraham por orden de Dios?","Babilonia","Egipto","Damasco","Ur de los caldeos",3,"Génesis 11,31; 12,1"],
["¿Cómo se llamaba la esposa de Abraham?","Rebeca","Raquel","Lea","Sara",3,"Génesis 17,15"],
["¿Cómo se llamaba el sobrino de Abraham?","Esaú","Ismael","Lot","Eliezer",2,"Génesis 12,5"],
["¿Cuántos años trabajó Jacob para casarse con Raquel la primera vez?","3","7","14","40",1,"Génesis 29,20"],
["¿Quién fue la madre de Moisés?","Miriam","Séfora","Débora","Jocabed",3,"Éxodo 6,20"],
["¿Qué dijo Jesús que era el mandamiento más grande de la ley?","No matar","Guardar el sábado","Amar a Dios con todo el corazón","Honrar al padre y la madre",2,"Mateo 22,37"],
["¿Qué oración enseñó Jesús a sus discípulos?","El Credo","El Ave María","El Magnificat","El Padrenuestro",3,"Mateo 6,9-13"],
["¿Cuántos evangelios hay en el Nuevo Testamento?","3","4","5","6",1,"Mateo, Marcos, Lucas, Juan"],
["¿Cuál es el evangelio más corto?","Mateo","Marcos","Lucas","Juan",1,"Marcos (16 capítulos)"],
["¿Cuál es el evangelio más largo?","Mateo","Marcos","Lucas","Juan",2,"Lucas (24 capítulos)"],
["¿Cuántos libros tiene el Nuevo Testamento?","24","27","29","30",1,"27 libros"],
["¿Cuántos libros tiene el Antiguo Testamento católico?","39","43","46","50",2,"46 libros"],
["¿Cuál es el último libro de la Biblia?","Daniel","Judas","Hebreos","Apocalipsis",3,"Apocalipsis"],
["¿Quién escribió el Apocalipsis?","Pablo","Pedro","Juan","Mateo",2,"Apocalipsis 1,1"],
["¿Quién era el discípulo amado de Jesús según la tradición?","Pedro","Santiago","Juan","Andrés",2,"Juan 13,23"],
["¿Cuál era el oficio de Pedro antes de seguir a Jesús?","Carpintero","Pescador","Pastor","Médico",1,"Mateo 4,18"],
["¿Cómo se llamaba el hermano de Pedro?","Juan","Santiago","Andrés","Felipe",2,"Mateo 4,18"],
["¿Quién fue el primer mártir cristiano?","Pedro","Pablo","Santiago","Esteban",3,"Hechos 7,59-60"],
["¿Cómo se llamaba Pablo antes de su conversión?","Simón","Esteban","Saulo","Nicanor",2,"Hechos 7,58"],
["¿Cómo se convirtió Pablo al cristianismo?","Por predicación de Pedro","Por un sueño","Por visión de Jesús en el camino a Damasco","Por leer las Escrituras",2,"Hechos 9,3-6"],
["¿Qué apóstol fue decapitado bajo Herodes?","Pedro","Juan","Felipe","Santiago",3,"Hechos 12,2"],
["¿Qué significa 'Evangelio'?","Carta sagrada","Ley de Dios","Historia antigua","Buena noticia",3,"Del griego εὐαγγέλιον"],
["¿Cuántos salmos hay en la Biblia?","100","120","150","200",2,"150 Salmos"],
["¿Cuál es el primer libro del Antiguo Testamento?","Éxodo","Levítico","Números","Génesis",3,"Génesis 1,1"],
["¿Cuáles son los cinco libros de Moisés?","Los profetas","Los Sapienciales","El Pentateuco","Los Salmos",2,"Génesis, Éxodo, Levítico, Números, Deuteronomio"],
["¿Quién fue la suegra de Rut?","Dalila","Débora","Ana","Noemí",3,"Rut 1,4"],
["¿En qué libro se cuenta la historia de la reina Ester?","Judit","Rut","Ester","Tobías",2,"Libro de Ester"],
["¿Qué profeta fue llevado al cielo sin morir?","Isaías","Ezequiel","Amós","Elías",3,"2 Reyes 2,11"],
["¿Cuántos libros proféticos hay en el Antiguo Testamento?","15","16","18","20",2,"18 libros proféticos"],
["¿Quién fue el profeta del exilio babilónico que tuvo visiones extraordinarias?","Jeremías","Amós","Oseas","Ezequiel",3,"Ezequiel 1,1"],
["¿Quién fue el ángel que anunció a María el nacimiento de Jesús?","Miguel","Rafael","Gabriel","Uriel",2,"Lucas 1,26-28"],
["¿A quién visitó María después de la Anunciación?","A Marta","A Ana la profetisa","A Rebeca","A su prima Isabel",3,"Lucas 1,39"],
["¿Qué dijo María cuando el ángel le anunció que sería madre de Jesús?","'No puede ser'","'Seré obediente'","'Soy tu sierva'","'Hágase en mí según tu palabra'",3,"Lucas 1,38"],
["¿Qué es el Magnificat?","La oración de Jesús","El canto profético de Zacarías","El canto de Simeón","El canto de alabanza de María",3,"Lucas 1,46-55"],
["¿Quién era Nicodemo?","Un pescador","Un soldado romano","Un fariseo y jefe de los judíos","Un recaudador de impuestos",2,"Juan 3,1"],
["¿Cuántos panes tuvo Jesús para alimentar a los 5000?","3","5","7","12",1,"Mateo 14,17"],
["¿Qué río cruzó Jesús para ser bautizado?","El Nilo","El Éufrates","El Tigris","El Jordán",3,"Mateo 3,13"],
["¿Cuántos días estuvo Jesús muerto antes de resucitar?","1","2","3","7",2,"Mateo 12,40"],
["¿Dónde ascendió Jesús al cielo?","En Belén","En Nazaret","En el Monte de los Olivos","En Galilea",2,"Hechos 1,12"],
["¿Cuántos días después de la Pascua bajó el Espíritu Santo?","7","30","50","100",2,"Pentecostés — 50 días"],
["¿Qué significa 'Pentecostés'?","El día de la resurrección","El bautismo","El día de la ascensión","Cincuenta días",3,"Del griego πεντηκοστή"],
["¿Qué signo se manifestó cuando bajó el Espíritu Santo?","Un arcoíris","Una paloma","Un trueno","Lenguas de fuego y viento",3,"Hechos 2,2-3"],
["¿Cuántas personas se bautizaron el día de Pentecostés?","120","300","3000","5000",2,"Hechos 2,41"],
["¿Quién predicó en Pentecostés?","Juan","Santiago","Pablo","Pedro",3,"Hechos 2,14"],
["¿Cómo se llama el libro que narra los orígenes de la Iglesia?","Cartas de Pablo","Apocalipsis","Evangelio de Juan","Hechos de los Apóstoles",3,"El libro de Hechos"],
["¿Cuántos capítulos tiene el Génesis?","40","50","60","70",1,"50 capítulos"],
["¿Quién presentó al niño Jesús en el Templo?","Los Reyes Magos","Los pastores","Los sacerdotes","María y José",3,"Lucas 2,22"],
["¿Quién reconoció a Jesús como el Mesías en el Templo cuando era niño?","Zacarías","Ananás","Caifás","Simeón",3,"Lucas 2,25-32"],
["¿Cuántos años tenía Jesús cuando se quedó en el Templo?","8","10","12","15",2,"Lucas 2,42"],
["¿Qué encontraron los pastores cuando llegaron a Belén?","A Jesús en el templo","A Jesús en una casa","A Jesús en un pesebre","A Jesús en el palacio",2,"Lucas 2,16"],
["¿Qué siguieron los Magos de Oriente para llegar a Jesús?","Un ángel","Una nube","Un profeta","Una estrella",3,"Mateo 2,2"],
["¿Quién ordenó matar a todos los niños menores de dos años en Belén?","Pilato","Arquelao","Antipas","Herodes el Grande",3,"Mateo 2,16"],
["¿A qué país huyó la Sagrada Familia para escapar de Herodes?","Grecia","Siria","Babilonia","Egipto",3,"Mateo 2,13-14"],
["¿Quién era el gobernador romano que condenó a Jesús a muerte?","Herodes","César","Antipas","Poncio Pilato",3,"Mateo 27,24-26"],
["¿Qué hizo Pilato para lavarse las manos del caso de Jesús?","Se fue del juicio","Firmó la sentencia","Liberó a un prisionero","Se lavó las manos con agua",3,"Mateo 27,24"],
["¿A quién liberó Pilato en lugar de Jesús?","Un zelote","Un asesino sin nombre","Barrabás","Simón el Cirineo",2,"Mateo 27,26"],
["¿En qué jardín oró Jesús la noche antes de ser arrestado?","En el Edén","En el jardín del Templo","En el jardín de José","En Getsemaní",3,"Mateo 26,36"],
["¿Con qué gesto traicionó Judas a Jesús?","Con un abrazo","Con un beso","Con un apretón de manos","Señalando con el dedo",1,"Mateo 26,48-49"],
["¿Quién cortó la oreja del siervo del sumo sacerdote?","Juan","Santiago","Judas","Pedro",3,"Juan 18,10"],
["¿A quién negó Pedro conocer tres veces?","A Juan","A Pilato","A Herodes","A Jesús",3,"Mateo 26,70-74"],
["¿Qué señal anunció Jesús a Pedro de que lo negaría?","El sonido de una trompeta","El llanto de María","El canto del gallo","Una estrella",2,"Mateo 26,34"],
["¿Quién bajó el cuerpo de Jesús de la cruz?","Pedro y Juan","Los soldados romanos","María Magdalena","José de Arimatea y Nicodemo",3,"Juan 19,38-39"],
["¿Quién fue el discípulo que dudó de la resurrección de Jesús?","Pedro","Juan","Felipe","Tomás",3,"Juan 20,24-25"],
["¿Qué hizo el padre cuando regresó el hijo pródigo?","Lo rechazó","Lo perdonó con castigo","Lo envió a trabajar","Hizo una fiesta en su honor",3,"Lucas 15,20-24"],
["¿Cómo se llamaba el ángel que anunció a Zacarías el nacimiento de Juan el Bautista?","Miguel","Rafael","Uriel","Gabriel",3,"Lucas 1,19"],
["¿Quién era el esposo de Isabel y padre de Juan el Bautista?","Simeón","Joaquín","Eliseo","Zacarías",3,"Lucas 1,5"],
["¿Cuál es el libro más corto de la Biblia?","2 Juan","3 Juan","Filemón","Abdías",1,"3 Juan — 1 capítulo, 14 versículos"],
["¿Qué profeta fue arrojado en un pozo por sus compatriotas?","Isaías","Ezequiel","Amós","Jeremías",3,"Jeremías 38,6"],
["¿Cuánto tiempo duró el exilio de Israel en Babilonia?","20 años","40 años","70 años","100 años",2,"Jeremías 25,11-12"],
["¿Quién destruyó el primer Templo de Jerusalén?","Los asirios","Los romanos","Los griegos","Los babilonios bajo Nabucodonosor",3,"2 Reyes 25,9"],
["¿Quién ordenó la reconstrucción del templo después del exilio?","Esdras","Nehemías","Darío","Ciro de Persia",3,"Esdras 1,1-4"],
["¿Quién era médico entre los evangelistas?","Mateo","Marcos","Juan","Lucas",3,"Colosenses 4,14"],
["¿Cuántas cartas escribió Pablo en el Nuevo Testamento?","9","11","13","15",2,"13 cartas paulinas"],
["¿Quién fue nombrado como sucesor de Judas por la comunidad cristiana?","Bernabé","Silas","Timoteo","Matías",3,"Hechos 1,26"],
["¿Qué significa 'Génesis'?","Libro de la ley","Historia de Moisés","Libro de los reyes","Principio / origen",3,"Del griego γένεσις"],
["¿Cuáles son los libros sinópticos?","Marcos, Lucas, Juan","Mateo, Juan, Hechos","Mateo, Marcos, Lucas","Marcos, Lucas, Hechos",2,"Los tres Sinópticos"],
["¿Quién fue el profeta que se casó con una mujer infiel como signo del amor de Dios?","Amós","Miqueas","Nahúm","Oseas",3,"Oseas 1,2"],
["¿Quién fue la profetisa que mató a Holofernes?","Ester","Rut","Débora","Judit",3,"Judit 13,8"],
["¿Qué significa 'Cristo'?","Siervo de Dios","El que salva","Ungido","Señor",2,"Del griego Χριστός"],
["¿Qué significa 'Mesías' en hebreo?","Siervo","Profeta","Ungido","Salvador",2,"Del hebreo מָשִׁיחַ (mashiach)"],
["¿Cuántos capítulos tiene el libro del Apocalipsis?","18","20","22","25",2,"22 capítulos"],
["¿Quién fue el rey de Babilonia que mandó arrojar a Daniel al foso?","Nabucodonosor","Ciro","Darío","Jerjes",2,"Daniel 6,17"],
["¿Cuántos años tenía Abrahán cuando nació Isaac?","80","90","100","110",2,"Génesis 21,5"],
["¿Qué río divide el jardín del Edén según el Génesis?","Solo el Nilo","Solo el Jordán","El Éufrates y el Tigris (entre otros)","Solo el Éufrates",2,"Génesis 2,10-14"],
["¿Qué dijo Jesús a sus discípulos sobre ser sal y luz?","Que debían huir del mundo","Que debían ser sal de la tierra y luz del mundo","Que el mundo los odiaría","Que debían orar en secreto",1,"Mateo 5,13-14"],
["¿Cómo se llamó el siervo de Abraham que buscó esposa para Isaac?","Lot","Eliezer","Ismael","Agar",1,"Génesis 15,2"],
["¿A qué país fue a parar José cuando fue vendido por sus hermanos?","Babilonia","Asiria","Moab","Egipto",3,"Génesis 37,28"],
["¿Cuántos hermanos vendieron a José?","5","8","10","11",2,"Génesis 37,28 — sus 10 hermanos varones"],
["¿Quién le prestó ropa a Moisés para ir ante el faraón?","Su hermana Miriam","Aarón","Nadie — ya era del palacio","El propio faraón",1,"Éxodo 28 — Aarón era el sacerdote"],
["¿Quién era el hermano de Moisés?","Josué","Eleazar","Caleb","Aarón",3,"Éxodo 4,14"],
["¿Cómo se llamaba la hermana de Moisés?","Débora","Noemí","Miriam","Séfora",2,"Éxodo 15,20"],
["¿Qué ciudad fue destruida por azufre y fuego en tiempos de Lot?","Nínive","Damasco","Sodoma y Gomorra","Jericó",2,"Génesis 19,24"],
["¿En qué se convirtió la esposa de Lot al mirar atrás?","En polvo","En piedra","En estatua de sal","En ceniza",2,"Génesis 19,26"],
["¿Qué lengua original tiene el Antiguo Testamento en su mayor parte?","Griego","Latín","Arameo","Hebreo",3,"La mayor parte del AT está en hebreo"],
["¿Qué lengua original tiene el Nuevo Testamento?","Latín","Hebreo","Griego","Arameo",2,"El NT fue escrito en griego koiné"],
["¿Cómo se llama la traducción de la Biblia al latín que se usó en la Iglesia durante siglos?","Septuaginta","Peshitta","Vulgata","Targum",2,"La Vulgata de San Jerónimo"],
["¿Cómo se llama la traducción de la Biblia al griego del Antiguo Testamento?","Vulgata","Septuaginta","Peshitta","Targum",1,"Septuaginta (LXX)"],
["¿Quién fue el que tradujo la Biblia al latín (Vulgata)?","San Agustín","San Jerónimo","San Ambrosio","San Gregorio",1,"San Jerónimo, siglo IV-V d.C."],
["¿Cuántos evangelistas hay?","2","3","4","5",2,"Mateo, Marcos, Lucas, Juan"],
["¿En qué mar no se puede hundir nadie por su alta salinidad?","Mar Mediterráneo","Mar de Galilea","Mar Muerto","Mar Rojo",2,"El Mar Muerto — 30% de salinidad"],
["¿Quién fue el rey que pidió la cabeza de Juan el Bautista?","Herodes el Grande","Poncio Pilato","Herodes Antipas","Arquelao",2,"Mateo 14,8-10"],
["¿A pedido de quién mandó Herodes decapitar a Juan el Bautista?","Su esposa Herodías","Su hija Salomé que bailó","Ambas — la hija pidió y la madre aconsejó","El sumo sacerdote",2,"Marcos 6,22-25"],
["¿Quién fue la gran profetisa del Antiguo Testamento que cantó la victoria sobre los egipcios?","Débora","Rut","Ana","Miriam",3,"Éxodo 15,20-21"],
["¿Cuánto tiempo duró la creación según el Génesis, incluyendo el descanso?","6 días","7 días","8 días","40 días",1,"Génesis 1,1-2,3"],
["¿Qué ciudad fue destruida por Josué y su ejército tras dar 7 vueltas y tocar trompetas?","Siquén","Hebrón","Hai","Jericó",3,"Josué 6"],
["¿Cuántas veces rodearon los israelitas Jericó el último día antes de que cayeran sus muros?","1","3","5","7",3,"Josué 6,15-16"],
["¿Cuáles son los libros históricos del Antiguo Testamento?","Génesis y Éxodo","Los Salmos","Josué, Jueces, Rut, Samuel, Reyes, etc.","Los libros de los profetas",2,"Josué hasta Macabeos"],
["¿A quién se atribuye el libro de los Proverbios?","Moisés","David","Ezequías","Salomón",3,"Proverbios 1,1"],
["¿Qué libro bíblico es un poema de amor?","Los Proverbios","La Sabiduría","El Sirácida","El Cantar de los Cantares",3,"Cantar de los Cantares"],
["¿A quién se atribuye el Cantar de los Cantares?","Moisés","David","Salomón","Qohélet",2,"Cantar de los Cantares 1,1"],
["¿Qué libro bíblico reflexiona sobre la vanidad de todo?","Proverbios","Sabiduría","Eclesiastés (Qohélet)","Sirácida",2,"Eclesiastés 1,2"],
["¿Cuáles son los libros sapienciales del AT?","Los profetas","Job, Salmos, Proverbios, Eclesiastés, Sabiduría, Sirácida, Cantar de los Cantares","Solo los Salmos","El Pentateuco",1,"Los 7 libros sapienciales"],
["¿Quién fue Job?","Un rey de Israel","Un profeta","Un sacerdote","Un hombre justo que sufrió mucho",3,"El libro de Job"],
["¿Quién fue el principal antagonista de los judíos en el libro de Ester?","Nabucodonosor","Holofernes","Amán","Hércules",2,"Ester 3,1-6"],
["¿Cuántos libros tiene el Pentateuco?","4","5","6","7",1,"Génesis, Éxodo, Levítico, Números, Deuteronomio"],
["¿Qué libro sigue al Génesis?","Levítico","Números","Deuteronomio","Éxodo",3,"Éxodo sigue a Génesis"],
["¿Cuántos capítulos tiene el libro de Isaías?","44","56","66","76",2,"66 capítulos"],
["¿Qué profeta tiene el libro más largo del Antiguo Testamento?","Ezequiel","Jeremías","Isaías","Daniel",1,"Jeremías — 52 capítulos"],
["¿Quién es el profeta del consuelo en el Antiguo Testamento?","Amós","Miqueas","Isaías","Oseas",2,"Isaías 40-55 — el Déutero-Isaías"],
["¿Cuántos libros de los Macabeos hay en la Biblia católica?","1","2","3","4",1,"1 y 2 Macabeos"],
["¿Cuándo comenzó la Iglesia católica a tener un canon bíblico definido?","Con Jesús","Con Pablo","Con el Concilio de Trento (1546) de modo definitivo","Con Constantino",2,"Concilio de Trento, 1546"],
["¿Qué significa 'Biblia'?","Libro sagrado","Los libros","Palabra de Dios","Ley divina",1,"Del griego βιβλία (biblía) — 'los libros'"],
["¿En cuántas partes se divide la Biblia?","En 3","En 4","En 2 — AT y NT","En 5",2,"Antiguo y Nuevo Testamento"],
["¿Qué otro nombre recibe el libro del Eclesiastés en hebreo?","Sirácida","Sabiduría","Proverbios","Qohélet",3,"Qohélet en hebreo"],
["¿Cuántos capítulos tiene el libro de Mateo?","26","28","30","32",1,"28 capítulos"],
["¿Cuántos capítulos tiene el libro de Juan?","19","21","23","25",1,"21 capítulos"],
["¿En qué ciudad fue bautizado Jesús?","Nazaret","Jerusalén","Cafarnaúm","En el río Jordán (Betania del otro lado del Jordán)",3,"Juan 1,28; Mateo 3,13"],
["¿Qué idioma hablaba Jesús en su vida cotidiana?","Griego","Latín","Hebreo","Arameo",3,"Jesús hablaba el arameo galileo"],
["¿Quién escribió la carta a los Romanos?","Pedro","Juan","Santiago","Pablo",3,"Romanos 1,1"],
["¿Cuál fue la primera comunidad cristiana importante fuera de Palestina?","Éfeso","Corinto","Roma","Antioquía de Siria",3,"Hechos 11,26 — en Antioquía los llamaron 'cristianos'"],
["¿Qué significa el nombre 'Jesús'?","Ungido","El que salva / Dios salva","Rey de Israel","Hijo de Dios",1,"Del hebreo Yeshua — 'Dios salva'"],
["¿Qué significa el nombre 'Emmanuel'?","El Mesías","El Señor","Dios con nosotros","El Salvador",2,"Mateo 1,23 — Is 7,14"],
["¿Quién fue el primer papa de la Iglesia?","Juan","Pablo","Pedro","Andrés",2,"Mateo 16,18"],
["¿Cuántas veces negó Pedro a Jesús?","2","3","4","5",1,"Mateo 26,70-74"],
["¿Qué río volvió a separar sus aguas para que Elías y Eliseo cruzaran?","El Nilo","El Éufrates","El Jordán","El Jaboc",2,"2 Reyes 2,8"],
["¿Quién fue el rey que mató a los profetas de Baal después del Carmelo?","El rey Acab","David","Elías (él mató, no un rey)","Josías",2,"1 Reyes 18,40"],
["¿En qué ciudad nació el rey David?","Belén","Hebrón","Nazaret","Jericó",0,"1 Samuel 17,12; Rut 4,22"],
["¿A quién dijo Pablo 'Eres mi hijo en la fe'?","Tito","Timoteo","Silas","Apolo",1,"1 Timoteo 1,2"],
["¿En qué libro de la Biblia se habla de la resurrección de los muertos de modo más explícito en el AT?","Ezequiel","Isaías","Daniel","Amós",2,"Daniel 12,2"],
["¿Quién fue el profeta que recibió la orden 'Ve y proclama en las calles de Nínive'?","Elías","Eliseo","Amós","Jonás",3,"Jonás 1,2"]
];
raw.forEach(function(r){
    allQuestions.push({question:r[0],options:[r[1],r[2],r[3],r[4]],answer:r[5],difficulty:1,money:100,isSafeHaven:false,source:r[6]});
});
})();
