// bank3.js - Nivel 3: Avanzado (200 preguntas)
(function() {
var raw = [
// [pregunta, A, B, C, D, respuesta(0-3), fuente]
["¿Cuál es la genealogía de Jesús en Mateo organizada?","Tres grupos de 14 generaciones cada uno","Cuatro grupos de 12 generaciones","Siete grupos de siete generaciones","Una lista continua sin grupos",0,"Mateo 1,17"],
["¿Cuántas mujeres aparecen en la genealogía de Mateo?","2","3","4","5",2,"Tamar, Rahab, Rut, la mujer de Urías (Betsabé) y María"],
["¿Quiénes son las cinco mujeres en la genealogía de Jesús según Mateo?","Sara, Rebeca, Raquel, Lea, María","Tamar, Rahab, Rut, Betsabé, María","Eva, Sara, Rebeca, Raquel, María","Rahab, Débora, Rut, Ana, María",1,"Mateo 1,3-16"],
["¿Cuántos versículos tiene el Salmo 117?","1","2","3","4",1,"Salmo 117 — 2 versículos, el más corto de la Biblia"],
["¿Cuál es el versículo central de toda la Biblia hebrea según el cómputo tradicional?","Salmo 118,8","Levítico 13,33","Proverbios 8,22","Isaías 33,21",0,"Sal 118,8 es considerado el versículo central"],
["¿Qué tipo de literatura es el libro de Job?","Narrativa histórica","Drama sapiencial en poesía","Profecía","Salmo de lamentación",1,"Job combina narración (prosa) con debate poético"],
["¿Cuántos discursos tiene Dios desde el torbellino en el libro de Job?","1","2","3","4",1,"Job 38-39 y 40-41 — dos discursos divinos"],
["¿Qué animal menciona Dios en su segundo discurso a Job como símbolo del caos?","El elefante","El hipopótamo (Behemot) y el cocodrilo (Leviatán)","El toro salvaje","El caballo de guerra",1,"Job 40,15-41,34"],
["¿Qué es el 'tohu wabohu' en Génesis 1,2?","El jardín del Edén","El caos primordial sin forma y vacío","El diluvio","El infierno",1,"Génesis 1,2 — תֹהוּ וָבֹהוּ"],
["¿Cuántos relatos de creación hay en el Génesis?","1","2","3","4",1,"Génesis 1,1-2,4a (sacerdotal) y 2,4b-25 (yahvista)"],
["¿Qué fuente bíblica usa principalmente el nombre 'Elohim' para Dios?","La fuente Yahvista (J)","La fuente Elohísta y Sacerdotal (E y P)","La fuente Deuteronomista (D)","El redactor final",1,"La tradición Elohísta (E) y Sacerdotal (P) usan Elohim"],
["¿Cuántas tradiciones documentales reconoce la Hipótesis Documentaria clásica (Wellhausen)?","2","3","4","5",2,"J, E, D, P — cuatro fuentes"],
["¿Qué fuente del Pentateuco se identifica con el estilo del Deuteronomio?","J (Yahvista)","E (Elohísta)","D (Deuteronomista)","P (Sacerdotal)",2,"La tradición Deuteronomista (D)"],
["¿Qué es la 'Obra Histórica Deuteronomista'?","El Pentateuco","Los profetas mayores","Josué, Jueces, Samuel y Reyes","Solo el Deuteronomio",2,"Josué-Reyes forman la OHD"],
["¿Cuántos capítulos ocupa el código sacerdotal en el libro del Levítico?","Todos","Los capítulos 1-16","Los capítulos 17-26 (Código de Santidad)","Solo el capítulo 19",2,"Levítico 17-26 — el 'Código de Santidad'"],
["¿Qué nombre recibe el código de Levítico 17-26?","Código del Sinaí","Código de la Alianza","Código de Santidad","Código Deuteronomístico",2,"Levítico 17-26 — Heiligkeitsgesetz"],
["¿Qué es el 'Código de la Alianza'?","El Decálogo","Éxodo 20,22-23,33","Levítico 1-7","El libro del Deuteronomio",1,"Éxodo 20,22-23,33 — la primera colección legal"],
["¿Cuántos capítulos tiene el Código de la Alianza?","3","4","5","6",0,"Éxodo 20,22-23,33 — 3 capítulos aproximadamente"],
["¿Qué significa 'Pentateuco'?","Cinco libros","Los libros de la ley","Los libros de Moisés","Libro sagrado",0,"Del griego πεντάτευχος — 'cinco libros'"],
["¿Cómo se llama la Torá en hebreo?","Los cinco rollos","La Ley","Torá — enseñanza, instrucción","Los mandamientos",2,"תּוֹרָה — Torá significa 'enseñanza'"],
["¿Qué significa 'Torá'?","Ley divina","Los mandamientos","La profecía","Enseñanza / instrucción",3,"תּוֹרָה — instrucción, enseñanza"],
["¿Cuántos mandamientos tiene la Ley de Moisés según la tradición judía?","248","365","613","1000",2,"613 mitzvot según la tradición rabínica"],
["¿Cuál es el texto hebreo que contiene el primer mandamiento del Decálogo?","'No tendrás otros dioses delante de mí'","'Yo soy el Señor tu Dios'","'No harás imágenes talladas'","'No tomarás en vano el nombre'",1,"Éxodo 20,2 — 'Anochi Adonai Elohecha'"],
["¿Qué diferencia hay entre el Decálogo de Éxodo 20 y el de Deuteronomio 5 sobre el sábado?","No hay diferencia","Ex 20 basa el sábado en la creación; Dt 5 en el éxodo de Egipto","Solo cambian las palabras pero no el sentido","Dt 5 tiene un mandamiento más",1,"Ex 20,11 vs Dt 5,15 — motivación diferente"],
["¿Cuántos capítulos tiene el libro de Deuteronomio?","32","33","34","35",2,"34 capítulos"],
["¿Qué estructura literaria tiene el Deuteronomio?","Una ley sin prólogo","Un código legal puro","Tres discursos de Moisés en forma de tratado de alianza","Un relato histórico",2,"Deuteronomio como tratado de alianza vasálica"],
["¿Cuántos discursos de Moisés contiene el Deuteronomio?","2","3","4","5",1,"3 discursos principales"],
["¿Cuál es la sección central del Deuteronomio que contiene la mayoría de las leyes?","Dt 1-4","Dt 5-28","Dt 29-34","Solo el capítulo 6",1,"Deuteronomio 5-28 — el corpus legal central"],
["¿Qué tipo de texto bíblico es el Cantar de los Cantares?","Una alegoría pura","Un poema de amor erótico con dimensión religiosa","Una profecía","Un salmo litúrgico",1,"El Cantar es poesía amorosa; la tradición lo interpretó como amor de Dios-Israel"],
["¿Quién debatió si el Cantar de los Cantares debía entrar al canon hebreo?","Los concilios eclesiales","Los rabinos en Jamnia","Los profetas","Los apóstoles",1,"En Jamnia (ca. 90 d.C.) se debatió su canonicidad"],
["¿Cuántos capítulos tiene el Cantar de los Cantares?","6","7","8","9",2,"8 capítulos"],
["¿Qué palabra hebrea que aparece en Eclesiastés 1,2 ('vanidad de vanidades') también significa 'vapor' o 'aliento'?","Ruah","Torah","Hesed","Hebel",3,"הֶבֶל (hebel) — vapor, vanidad"],
["¿Cuántos capítulos tiene el Eclesiastés?","10","11","12","13",2,"12 capítulos"],
["¿Qué libro del AT tiene el texto hebreo más cercano al arameo?","Génesis","Job","Daniel","Ezequiel",2,"Daniel tiene secciones en arameo (Dn 2,4b-7,28)"],
["¿En qué lengua están escritas partes del libro de Daniel?","Griego","Latín","Siriaco","Arameo",3,"Daniel 2,4b-7,28 está en arameo"],
["¿Cuántos capítulos tiene el libro de Daniel?","10","12","14","16",1,"12 capítulos"],
["¿Qué tipo de literatura predomina en el libro de Daniel?","Profecía clásica","Apocalíptica","Sapiencial","Histórica",1,"Daniel es el gran texto apocalíptico del AT"],
["¿En qué año aproximado fue escrito el libro de Daniel en su forma final?","Siglo VI a.C.","Siglo V a.C.","Siglo IV a.C.","Siglo II a.C.",3,"ca. 165 a.C., durante la persecución de Antíoco IV Epífanes"],
["¿Quién fue Antíoco IV Epífanes?","Un rey babilónico","Un rey persa","Un rey seléucida que profanó el Templo","Un faraón egipcio",2,"Antíoco IV Epífanes, rey seléucida, 175-164 a.C."],
["¿Qué se llama 'la abominación desoladora' en Daniel?","El exilio babilónico","La destrucción del Templo por Nabucodonosor","La profanación del Templo por Antíoco IV","La invasión romana",2,"Daniel 9,27; 1 Macabeos 1,54"],
["¿Cuántos libros tiene el canon de la Biblia hebrea (TaNaK)?","24","36","39","46",0,"24 libros en el TaNaK (equivalen a los 39 protestantes)"],
["¿Qué significa TaNaK?","Los tres partes de la Biblia hebrea: Torá, Nebiim, Ketuvim","El Templo de Dios","La alianza de Dios","La ley sagrada",0,"ת נ ך — Torá, Nebiim (Profetas), Ketuvim (Escritos)"],
["¿Cuántos libros tiene la sección de los Nebiim (Profetas) en el canon hebreo?","6","7","8","9",2,"8 libros: Profetas Anteriores (4) + Posteriores (4)"],
["¿Qué son los 'Profetas Anteriores' en el TaNaK?","Isaías, Jeremías, Ezequiel, los Doce","Josué, Jueces, Samuel, Reyes","Los Salmos y Job","El Pentateuco",1,"Nebiim Rishonim: Josué, Jueces, Samuel, Reyes"],
["¿Qué son los 'Ketuvim' en el TaNaK?","Los profetas","La Torá","Los Escritos — Salmos, Proverbios, Job, etc.","Solo los Salmos",2,"Ketuvim = Escritos, tercera sección del TaNaK"],
["¿Cuántos libros tiene la sección de los Ketuvim (Escritos)?","9","10","11","12",2,"11 libros en los Ketuvim"],
["¿Cuál es la primera versión griega del Antiguo Testamento?","La Vulgata","La Peshitta","La Septuaginta (LXX)","El Tárgum",2,"La Septuaginta, ca. siglo III-II a.C."],
["¿Por qué se llama la Septuaginta con el número 70 (LXX)?","Porque tiene 70 libros","Porque fueron 70 (o 72) traductores según la tradición","Porque se tradujo en 70 días","Porque fue aprobada por 70 rabinos",1,"Según la Carta de Aristeas, 72 traductores (70 por redondeo)"],
["¿En qué ciudad se realizó la traducción de la Septuaginta?","Jerusalén","Babilonia","Roma","Alejandría",3,"Alejandría, Egipto — centro de la diáspora judía"],
["¿Qué es un 'Tárgum'?","Una traducción al griego","Una traducción/paráfrasis al arameo del AT","Un comentario rabínico","Una versión latina",1,"Tárgum = versión aramea interpretativa del AT"],
["¿Qué es la Peshitta?","La versión griega","La versión latina","La versión siríaca de la Biblia","La versión copta",2,"La Peshitta — versión siríaca de la Biblia"],
["¿En qué siglo vivió San Jerónimo, el traductor de la Vulgata?","Siglo II","Siglo III","Siglo IV-V","Siglo VI",2,"San Jerónimo, ca. 347-420 d.C."],
["¿Dónde vivió San Jerónimo durante la mayoría de su trabajo de traducción?","Roma","Antioquía","Alejandría","Belén",3,"San Jerónimo vivió en Belén mientras traducía"],
["¿Cuántas versículos tiene el Salmo 119?","176","178","180","182",0,"176 versículos — el más largo de la Biblia"],
["¿Qué estructura especial tiene el Salmo 119?","Es un himno litúrgico simple","Es un salmo acróstico: 22 estrofas de 8 versículos cada una según el alfabeto hebreo","Es un poema de amor","Es un salmo histórico",1,"Salmo 119 — acróstico sobre las 22 letras del alef-bet"],
["¿Qué término hebreo describe la lealtad amorosa de Dios hacia su pueblo?","Shalom","Emunah","Hesed","Emet",2,"חֶסֶד (hesed) — amor fiel, misericordia"],
["¿Qué término hebreo significa 'justicia' en el AT?","Hesed","Tsedakah","Emet","Ruah",1,"צְדָקָה (tsedaqah) — justicia, rectitud"],
["¿Qué término hebreo significa 'espíritu / viento / aliento'?","Hesed","Logos","Ruah","Nefesh",2,"רוּחַ (ruah) — espíritu, viento, aliento"],
["¿Qué significa el hebreo 'nefesh' (נֶפֶשׁ)?","Espíritu inmortal","Cuerpo físico","Ser viviente / vida / persona","Mente racional",2,"נֶפֶשׁ — ser vivo, vida, persona (no dualismo griego)"],
["¿Qué término griego del NT corresponde al concepto hebreo de 'nefesh'?","Pneuma","Soma","Sarx","Psyché",3,"ψυχή (psyché) — vida, ser viviente"],
["¿Qué significa el griego 'pneuma' (πνεῦμα)?","Cuerpo","Mente","Alma","Espíritu / viento / aliento",3,"πνεῦμα — espíritu, aliento, viento"],
["¿Qué significa el griego 'logos' (λόγος) en Juan 1,1?","Palabra, pero también Razón / Sentido","Solo 'discurso'","Ley divina","Mandamiento",0,"Logos — palabra, razón, sentido cósmico"],
["¿En qué versículo dice Juan 'el Logos se hizo carne'?","Juan 1,1","Juan 1,9","Juan 1,14","Juan 1,18",2,"Juan 1,14 — 'el Verbo se hizo carne'"],
["¿Qué término usa Juan para describir la encarnación del Verbo?","Theosis","Kenosis","La sarx (carne)","La skené (tienda/tabernáculo)",2,"Juan 1,14 — ἐσκήνωσεν (habitó como en tienda entre nosotros)"],
["¿Qué término paulino describe el 'vaciamiento' de Cristo al encarnarse?","Theosis","Plerosis","Kenosis","Parousia",2,"Filipenses 2,7 — ἐκένωσεν (se vació a sí mismo)"],
["¿Cuántas 'antítesis' tiene el Sermón del Monte ('Habéis oído... pero yo os digo')?","4","5","6","7",2,"Mateo 5,21-48 — 6 antítesis"],
["¿En qué versículo Jesús dice 'No he venido a abolir la Ley sino a darle cumplimiento'?","Mateo 5,13","Mateo 5,17","Mateo 5,20","Mateo 5,44",1,"Mateo 5,17"],
["¿Cuántos capítulos ocupa el Sermón del Monte?","1","2","3","4",2,"Mateo 5, 6 y 7 — 3 capítulos"],
["¿Qué discurso de Jesús en Mateo habla del fin del mundo?","El Sermón del Monte","El Discurso de Misión","El Discurso del Pan de Vida","El Discurso Escatológico",3,"Mateo 24-25 — el Discurso Escatológico"],
["¿Cuántos discursos grandes tiene Mateo?","3","4","5","6",2,"5 discursos: Mt 5-7, 10, 13, 18, 24-25"],
["¿Qué estructura literaria usa Mateo que recuerda al Pentateuco?","Tres relatos alternados","Cinco discursos alternados con narrativas","Siete secciones","Cuatro partes",1,"Los 5 discursos de Mateo evocan los 5 libros de Moisés"],
["¿En qué capítulo de Marcos Jesús hace el Discurso Escatológico?","Marcos 10","Marcos 11","Marcos 13","Marcos 14",2,"Marcos 13 — el 'Discurso Escatológico'"],
["¿Qué término griego se usa en el NT para la segunda venida de Cristo?","Epifanía","Parousia","Apokalypsis","Eschaton",1,"Παρουσία (parousia) — venida, presencia"],
["¿Qué significa 'maranatha' (מָרַן אֲתָא)?","Gracias a Dios","Señor, ven","Aleluya","Amén",1,"Arameo — 'Señor, ven' (1 Co 16,22; Ap 22,20)"],
["¿En qué lengua está escrita la frase 'maranatha' del NT?","Hebreo","Griego","Arameo","Latín",2,"Arameo — מָרַן אֲתָא"],
["¿Qué significa 'Aleluya' (הַלְּלוּיָהּ)?","Gloria a Dios","Amén","Alabanza a Yahvé","Bendito seas",2,"הַלְּלוּיָהּ — 'Alabad a Yahvé'"],
["¿En qué capítulo de Hechos describe Lucas la primera comunidad cristiana de Jerusalén?","Hechos 1","Hechos 2","Hechos 3","Hechos 4",1,"Hechos 2,42-47 — la koinonía original"],
["¿Qué cuatro elementos caracterizan la primera comunidad cristiana según Hch 2,42?","Oración, ayuno, misión, milagros","Enseñanza apostólica, comunión, fracción del pan, oración","Eucaristía, bautismo, confirmación, penitencia","Predicación, curación, exorcismo, misión",1,"Hechos 2,42 — didajé, koinonía, fracción, proseuché"],
["¿Qué es la 'koinonía' en el NT?","Un salmo litúrgico","La enseñanza apostólica","La comunión / participación fraternal","La oración comunitaria",2,"Κοινωνία — comunión, participación, fraternidad"],
["¿Cuántas comunidades fundó Pablo en su primer viaje misionero?","2","3","4","5",2,"Antioquía de Pisidia, Iconio, Listra, Derbe — 4"],
["¿En qué ciudad tuvo Pablo la visión del macedonio que le pedía ayuda?","Antioquía","Éfeso","Tróade","Corinto",2,"Hechos 16,8-10 — la visión en Tróade"],
["¿Cuánto tiempo estuvo Pablo en Corinto en su segundo viaje?","6 meses","1 año","18 meses","3 años",2,"Hechos 18,11 — año y medio"],
["¿Cuánto tiempo estuvo Pablo en Éfeso en su tercer viaje?","1 año","2 años","3 años","5 años",2,"Hechos 19,10 — 2 años en Éfeso (algunos dicen más)"],
["¿En qué ciudad fue Pablo arrestado por última vez antes de ir a Roma?","Éfeso","Corinto","Cesarea Marítima","Jerusalén",3,"Hechos 21,27-28 — arrestado en Jerusalén"],
["¿Cuánto tiempo estuvo Pablo preso en Cesarea?","1 año","2 años","3 años","4 años",1,"Hechos 24,27 — 2 años bajo Félix y Festo"],
["¿Qué invocó Pablo para ser juzgado por el César?","Su ciudadanía romana","Su carácter de apóstol","La ley judía","Un milagro divino",0,"Hechos 25,11 — 'Apelo al César'"],
["¿Qué figura literaria usa Isaías cuando dice 'los montes y los collados prorrumpirán en gritos'?","Metáfora","Símbolo","Personificación","Hipérbole",2,"Isaías 55,12 — personificación de la naturaleza"],
["¿Qué es el 'paralelismo' en la poesía hebrea?","La rima final de los versos","La repetición de ideas en versos paralelos","La métrica de sílabas","El estribillo",1,"El paralelismo sinónimo, antitético y sintético"],
["¿Cuántos tipos principales de paralelismo hebreo existen?","2","3","4","5",1,"Sinónimo, antitético y sintético — 3 tipos principales"],
["¿Qué es el paralelismo sinónimo en la poesía hebrea?","Opone dos ideas contrarias","Repite la misma idea con palabras distintas","Añade información nueva al primer verso","Usa un refrán al final",1,"El segundo hemistiquio repite el primero con sinónimos"],
["¿Qué es el paralelismo antitético?","Repite la misma idea","Opone ideas contrarias en los versos","Completa la idea del primer verso","Usa una imagen distinta",1,"Proverbios 10 usa mucho el paralelismo antitético"],
["¿Qué forma literaria es el Salmo 22?","Himno de alabanza","Cántico de Sion","Lamentación individual","Salmo real",2,"Salmo 22 — lamentación individual que termina en alabanza"],
["¿Cuántos tipos de salmos reconoce la tipología de Hermann Gunkel?","3","4","5","6",2,"Gunkel: himno, lamentación individual/colectiva, acción de gracias, real, sapiencial"],
["¿Qué es un 'salmo de peregrinación' (o de las subidas)?","Un salmo funeral","Los salmos 120-134 cantados en las peregrinaciones al Templo","Un salmo de entronización","Un salmo real",1,"Salmos 120-134 — Shir HaMa'alot"],
["¿Cuántos salmos de peregrinación hay?","12","13","14","15",3,"Salmos 120-134 — 15 salmos"],
["¿Qué acontecimiento describe el Salmo 137 ('Junto a los ríos de Babilonia')?","El cruce del Mar Rojo","El exilio en Babilonia","La conquista de Canaán","El llanto por el Templo destruido",1,"Salmo 137 — lamento del exilio babilónico"],
["¿Qué ciudad llora el salmista en el Salmo 137?","Samaria","Nínive","Jerusalén (Sión)","Babilonia",2,"'Si me olvido de ti, Jerusalén...' (Sal 137,5)"],
["¿Qué tiene de especial el libro de los Proverbios 31,10-31?","Es un poema acróstico sobre la mujer fuerte","Es un himno litúrgico","Es una profecía mesiánica","Es la conclusión del libro",0,"Proverbios 31,10-31 — אֵשֶׁת חַיִל, acróstico alfabético"],
["¿Cuántos capítulos tiene el libro de los Proverbios?","28","30","31","33",2,"31 capítulos"],
["¿Qué es la 'sabiduría personificada' en Proverbios 8?","Un nombre de Dios","Una figura femenina divina que estaba con Dios en la creación","Un ángel especial","El Espíritu Santo",1,"Proverbios 8,22-31 — la Sabiduría como figura preexistente"],
["¿En qué versículo de Proverbios 8 dice la Sabiduría 'El Señor me creó al principio de su obra'?","Pr 8,1","Pr 8,15","Pr 8,22","Pr 8,30",2,"Proverbios 8,22 — debatido: 'qanani' = creó o adquirió"],
["¿Cuántos capítulos tiene el libro de la Sabiduría?","16","18","19","20",2,"19 capítulos"],
["¿En qué libro del AT aparece la doctrina más clara de la inmortalidad del alma?","Job","Eclesiastés","Sabiduría","Daniel",2,"Sabiduría 3,1-9 — 'las almas de los justos están en manos de Dios'"],
["¿Cuántos capítulos tiene el libro del Sirácida (Eclesiástico)?","48","50","51","53",2,"51 capítulos"],
["¿Cómo se llama el libro del Sirácida en español?","Sabiduría","Eclesiastés","Eclesiástico","Baruc",2,"Ben Sira / Sirácida / Eclesiástico"],
["¿Quién escribió el Sirácida?","Salomón","Ben Sira de Jerusalén (ca. 180 a.C.)","Un sabio anónimo del exilio","Esdras",1,"Jesús Ben Sira, Jerusalén, ca. 180 a.C."],
["¿Cuántos capítulos tiene el libro de Baruc?","5","6","7","8",1,"6 capítulos"],
["¿Quién era Baruc según el AT?","Un rey de Israel","El secretario y discípulo del profeta Jeremías","Un sacerdote del Templo","Un sabio de la diáspora",1,"Baruc ben Neriyá — secretario de Jeremías (Jr 36,4)"],
["¿Cuántos capítulos tienen los cuatro evangelios juntos?","85","89","91","95",1,"Mt 28 + Mc 16 + Lc 24 + Jn 21 = 89 capítulos"],
["¿En qué evangelio Jesús aparece como el nuevo Moisés?","Marcos","Lucas","Juan","Mateo",3,"Mateo — Jesús como nuevo Moisés y nueva Torá"],
["¿En qué evangelio predomina la imagen de Jesús como profeta que camina hacia Jerusalén?","Mateo","Marcos","Juan","Lucas",3,"Lucas — la gran sección del 'viaje' (9,51-19,27)"],
["¿Qué capítulo de Lucas contiene el 'Evangelio de la Misericordia' con tres parábolas?","Lucas 12","Lucas 14","Lucas 15","Lucas 16",2,"Lucas 15 — oveja, moneda, hijo pródigo"],
["¿En qué evangelio predomina la imagen de Jesús como 'la Luz del mundo' y el Verbo preexistente?","Mateo","Marcos","Lucas","Juan",3,"Juan — el evangelio espiritual y teológico"],
["¿Cuántos 'signos' (milagros) relata el Evangelio de Juan?","5","7","8","9",1,"Los 7 signos de Juan (aunque algunos cuentan 8)"],
["¿Cuál es el último signo del Libro de los Signos en Juan?","La multiplicación de panes","La resurrección de Lázaro","La curación del ciego","La boda de Caná",1,"Juan 11 — la resurrección de Lázaro es el 7° signo"],
["¿Cómo se llama la sección de Juan 1-12?","El Libro de la Gloria","El Libro de los Signos","El Prólogo","El Discurso de Despedida",1,"Juan 1-12 — Libro de los Signos"],
["¿Cómo se llama la sección de Juan 13-20?","El Libro de los Signos","El Prólogo","El Libro de la Gloria","El Epílogo",2,"Juan 13-20 — Libro de la Gloria"],
["¿Qué capítulo de Juan contiene los Discursos de Despedida de Jesús?","Juan 10-12","Juan 13-17","Juan 18-19","Juan 20-21",1,"Juan 13-17 — los discursos de la noche antes de la pasión"],
["¿En qué capítulo de Juan Jesús ora la 'oración sacerdotal' o 'oración por la unidad'?","Juan 14","Juan 15","Juan 16","Juan 17",3,"Juan 17 — la Gran Oración Sacerdotal"],
["¿Cuántos versículos tiene la oración sacerdotal de Jesús (Juan 17)?","24","26","28","30",1,"26 versículos"],
["¿Qué figura usa Jesús en Juan 15 para describir su relación con los discípulos?","El pan","La puerta","La vid y los sarmientos","El buen pastor",2,"Juan 15,1-8 — 'Yo soy la vid, vosotros los sarmientos'"],
["¿En qué capítulo de Juan Jesús declara 'Yo soy el buen pastor'?","Juan 8","Juan 9","Juan 10","Juan 11",2,"Juan 10,11.14"],
["¿Qué significa 'paráclito' (παράκλητος) en el Evangelio de Juan?","El que ora","El que consuela / el abogado / el intercesor","El que profetiza","El ángel mensajero",1,"Paráclito — defensor, consolador, intercesor (Jn 14,16)"],
["¿Cuántas veces menciona Juan la palabra 'paráclito'?","3","4","5","6",2,"5 veces: Juan 14,16.26; 15,26; 16,7; 1 Juan 2,1"],
["¿Qué texto del AT es el más citado en el NT?","Génesis","Éxodo","Deuteronomio","Salmos",3,"Los Salmos son el libro más citado del NT"],
["¿Qué figura del AT es más usada en el NT para hablar de Cristo?","El rey David","El profeta Elías","El Siervo Sufriente de Isaías 53","El sumo sacerdote",2,"Isaías 53 — el Siervo Sufriente como tipo de Cristo"],
["¿Qué carta del NT contiene la mayor cantidad de citas del AT?","Efesios","Romanos","Hebreos","Gálatas",2,"Hebreos tiene la mayor densidad de citas del AT"],
["¿Qué término usa la carta a los Hebreos para describir los ritos del AT respecto a Cristo?","Figuras","Sombras","Tipos","Imágenes",1,"Hebreos 8,5; 10,1 — σκιά (sombra)"],
["¿Cuántos capítulos tiene la Primera carta de Juan?","4","5","6","7",1,"5 capítulos"],
["¿Qué dice 1 Juan sobre la relación entre el amor a Dios y el amor al hermano?","Son independientes","El que no ama al hermano no puede amar a Dios","Primero hay que amar a Dios","Son iguales en importancia",1,"1 Juan 4,20-21"],
["¿Qué afirma 1 Juan 4,8 sobre la naturaleza de Dios?","Dios es amor (ὁ θεὸς ἀγάπη ἐστίν)","Dios es todopoderoso","Dios es luz","Dios es espíritu",0,"1 Juan 4,8.16 — ὁ θεὸς ἀγάπη ἐστίν"],
["¿Qué término griego del NT describe el amor incondicional y sacrificial?","Eros","Philia","Storge","Agape",3,"Ἀγάπη (agapé) — amor incondicional"],
["¿Qué término usa el AT en hebreo para el amor de Dios como padre y esposo?","Emunah","Tsedakah","Hesed","Emet",2,"חֶסֶד (hesed) — amor fiel, misericordia"],
["¿En qué profeta del AT está la profecía 'He aquí que llegan días en que haré una nueva alianza'?","Isaías","Ezequiel","Amós","Jeremías",3,"Jeremías 31,31"],
["¿Qué libro del NT aplica más explícitamente la 'nueva alianza' de Jeremías 31 a Jesús?","Romanos","Gálatas","Hebreos","Efesios",2,"Hebreos 8,8-12 cita Jr 31,31-34"],
["¿En qué versículo Pablo cita la Nueva Alianza en el contexto de la Eucaristía?","1 Co 10,16","1 Co 11,23","1 Co 11,25","1 Co 15,3",2,"1 Corintios 11,25 — 'esta copa es la nueva alianza en mi sangre'"],
["¿Cuántos tipos de literatura hay en el NT?","3","4","5","6",1,"Evangelios, Hechos, Cartas, Apocalipsis — 4 géneros"],
["¿Cuántas cartas hay en el NT?","19","20","21","22",2,"21 cartas en el NT"],
["¿Cuántas cartas paulinas hay en el NT?","11","12","13","14",2,"13 cartas atribuidas a Pablo"],
["¿Cuántas cartas católicas (o universales) hay en el NT?","5","6","7","8",2,"7 cartas: Santiago, 1-2 Pedro, 1-2-3 Juan, Judas"],
["¿Cómo se llaman las cartas de Pablo escritas desde la prisión?","Cartas pastorales","Cartas de la cautividad","Cartas menores","Cartas apostólicas",1,"Efesios, Filipenses, Colosenses, Filemón — cartas de la cautividad"],
["¿Qué afirma Pablo sobre la resurrección de Cristo en 1 Co 15,17?","'Si Cristo no resucitó, predicamos en vano'","'Si Cristo no resucitó, vuestra fe es vana'","'Si Cristo no resucitó, aún estáis en vuestros pecados'","Las tres son versículos del mismo pasaje",3,"1 Co 15,14-17 — son tres argumentos encadenados"],
["¿Cuántos testigos de las apariciones de Cristo resucitado menciona Pablo en 1 Co 15?","3 grupos","4 grupos","5 grupos","6 grupos",2,"1 Co 15,5-8 — Cefas, 12, 500, Santiago, apóstoles, Pablo"],
["¿A cuántos habló el resucitado de una sola vez según 1 Co 15,6?","120","300","500","1000",2,"1 Corintios 15,6 — 'más de quinientos hermanos'"],
["¿Qué carta de Pablo es considerada su 'testamento teológico'?","Gálatas","1 Corintios","Filipenses","Romanos",3,"Romanos — la síntesis teológica de Pablo"],
["¿En qué capítulo de Romanos desarrolla Pablo la doctrina de la justificación por la fe?","Romanos 1-2","Romanos 3-4","Romanos 5-6","Romanos 8",1,"Romanos 3,21-4,25 — la justificación"],
["¿Qué término griego usa Pablo para 'justificación'?","Soteria","Dikaiosyne","Pistis","Charis",1,"Δικαιοσύνη (dikaiosyne) — justicia/justificación"],
["¿Cuántos capítulos tiene la carta a los Efesios?","4","5","6","7",2,"6 capítulos"],
["¿Qué imagen usa Pablo en Efesios 5 para describir la relación de Cristo y la Iglesia?","El padre y los hijos","El rey y sus súbditos","El esposo y la esposa","El pastor y el rebaño",2,"Efesios 5,25-32 — el matrimonio como imagen de Cristo-Iglesia"],
["¿Cuántos capítulos tiene la carta a los Colosenses?","3","4","5","6",1,"4 capítulos"],
["¿Qué es la 'plenitud' (pleroma) en Colosenses?","La Iglesia","El Espíritu Santo","La totalidad de la divinidad que habita en Cristo","El reino de Dios",2,"Colosenses 1,19; 2,9 — πλήρωμα"],
["¿Cuántos capítulos tiene la primera carta a los Tesalonicenses?","4","5","6","7",1,"5 capítulos"],
["¿Por qué es importante la 1 carta a los Tesalonicenses?","Es la más larga de Pablo","Es la primera carta del NT en escribirse (ca. 50 d.C.)","Es la carta más teológica","Es la que habla más de la resurrección",1,"1 Tesalonicenses — ca. 50 d.C., primera carta del NT"],
["¿En qué texto Pablo habla de 'ponerse la armadura de Dios'?","Romanos 13","Efesios 6","Colosenses 3","Filipenses 4",1,"Efesios 6,10-17 — la armadura espiritual"],
["¿Cuántas piezas tiene la 'armadura de Dios' en Efesios 6?","5","6","7","8",1,"6 piezas: cinturón, coraza, calzado, escudo, casco, espada"]
];
raw.forEach(function(r){
    allQuestions.push({question:r[0],options:[r[1],r[2],r[3],r[4]],answer:r[5],difficulty:3,money:1000,isSafeHaven:false,source:r[6]});
});
})();
